(()=>{'use strict';
window.UNIBRIGHT_BUILD='20260911-v17-exact-a4';
function visible(el){if(!el)return false;const r=el.getBoundingClientRect(),s=getComputedStyle(el);return s.display!=='none'&&s.visibility!=='hidden'&&r.width>250&&r.height>350}
function score(el){if(!el)return-1;let n=0;const c=String(el.className||''),t=(el.innerText||'').toUpperCase();if(c.includes('a4-sheet'))n+=100;if(c.includes('ub-a4'))n+=95;if(el.tagName==='ARTICLE')n+=40;if(/INVOICE|QUOTATION|RECEIPT|報價單|付款通知單|收據/.test(t))n+=60;if(el.querySelectorAll('table').length>=2)n+=30;if(visible(el))n+=50;const r=el.getBoundingClientRect();if(r.width>500&&r.height>700)n+=25;return n}
function findDoc(){const roots=[document.querySelector('.single-preview'),document.querySelector('.preview-stage'),document.getElementById('app'),document.body].filter(Boolean),sels=['.a4-sheet','.ub-a4','.a4-scale-box>article','.a4-scale-box>*','.preview-stage article','.single-preview article','article'];let list=[];for(const root of roots){for(const sel of sels){try{root.querySelectorAll(sel).forEach(x=>list.push(x))}catch(_){}}}list=[...new Set(list)].filter(x=>score(x)>50).sort((a,b)=>score(b)-score(a));return list[0]||null}
function normalize(src){const c=src.cloneNode(true);if(!c.classList.contains('a4-sheet'))c.classList.add('a4-sheet');Object.assign(c.style,{transform:'none',transformOrigin:'top left',margin:'0',boxShadow:'none',width:'794px',height:'1123px',minHeight:'1123px',maxHeight:'1123px',overflow:'hidden',background:'#fff',position:'relative'});return c}
async function ensureLibs(){if(!window.html2canvas){await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js';s.onload=res;s.onerror=()=>rej(new Error('html2canvas 載入失敗'));document.head.appendChild(s)})}if(!(window.jspdf&&window.jspdf.jsPDF)){await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';s.onload=res;s.onerror=()=>rej(new Error('jsPDF 載入失敗'));document.head.appendChild(s)})}}
async function exactBlob(){const src=findDoc();if(!src)throw new Error('畫面上搵唔到正式 A4 文件');await ensureLibs();if(document.fonts?.ready)await document.fonts.ready;const clone=normalize(src),host=document.createElement('div');host.style.cssText='position:fixed;left:-10000px;top:0;width:794px;height:1123px;overflow:hidden;background:#fff;z-index:-1;pointer-events:none';host.appendChild(clone);document.body.appendChild(host);try{await Promise.all([...clone.querySelectorAll('img')].map(async im=>{try{if(im.decode)await im.decode()}catch(_){}}));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const canvas=await window.html2canvas(clone,{backgroundColor:'#ffffff',scale:2,useCORS:true,allowTaint:true,logging:false,width:794,height:1123,windowWidth:794,windowHeight:1123,scrollX:0,scrollY:0,x:0,y:0});if(!canvas||canvas.width<1500||canvas.height<2200)throw new Error('A4 畫布建立失敗');const {jsPDF}=window.jspdf,pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});const img=canvas.toDataURL('image/jpeg',0.98);pdf.addImage(img,'JPEG',0,0,210,297,undefined,'FAST');const blob=pdf.output('blob');if(!blob||blob.size<1000)throw new Error('PDF 建立失敗');return blob}finally{host.remove()}}
function filename(){const src=findDoc(),txt=src?.innerText||document.body.innerText||'',title=/RECEIPT|收據/i.test(txt)?'Receipt':/INVOICE|付款通知單/i.test(txt)?'Invoice':'Quotation',no=txt.match(/(?:QO|TQ|INV|RCP|RC)[A-Z0-9\/-]*/i)?.[0]||new Date().toISOString().slice(0,10);return `UNIBRIGHT_${title}_${String(no).replace(/[\\/:*?"<>|]+/g,'-')}.pdf`}
window.downloadCurrentPDF=window.exportCurrentPDF=async function(name){let popup=null;try{const isMobile=/iPhone|iPad|iPod|Android/i.test(navigator.userAgent);if(isMobile){try{popup=window.open('','_blank');if(popup)popup.document.write('<meta name="viewport" content="width=device-width"><p style="font-family:sans-serif;padding:24px">正在建立 A4 PDF…</p>')}catch(_){}}const blob=await exactBlob(),fn=name||filename(),file=new File([blob],fn,{type:'application/pdf'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){if(popup)popup.close();try{await navigator.share({files:[file],title:fn});return true}catch(e){if(e?.name==='AbortError')return false}}const url=URL.createObjectURL(blob);if(isMobile){if(popup)popup.location.replace(url);else location.href=url}else{const a=document.createElement('a');a.href=url;a.download=fn;document.body.appendChild(a);a.click();a.remove()}setTimeout(()=>URL.revokeObjectURL(url),300000);return true}catch(e){if(popup)popup.close();console.error('V17 exact PDF',e);alert('PDF 下載失敗：'+String(e?.message||e));return false}};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const t=(b.textContent||'').replace(/\s+/g,' ').trim();if(t==='下載 PDF'||t==='下載／儲存 PDF'||t==='下載 / 儲存 PDF'){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();window.downloadCurrentPDF();}},true);
window.UNIBRIGHT_V17=()=>({doc:!!findDoc(),html2canvas:!!window.html2canvas,jspdf:!!window.jspdf?.jsPDF,pdf:typeof window.downloadCurrentPDF==='function'});
})();