(()=>{
const logo=()=>`<img class="ub-doc-logo" src="${window.UNIBRIGHT_LOGO||''}" alt="UNIBRIGHT CONSTRUCTION (H.K.) LTD.">`;
formalHeader=function(title,sub){return `<div class="ub-doc-head"><div class="ub-logo-wrap">${logo()}</div><div class="ub-doc-title"><b>${title}</b><span>${sub}</span></div></div>`};
formalItems=function(items){return `<table class="ub-items"><thead><tr><th class="desc">施工項目</th><th>單位</th><th>數量</th><th class="money">單價</th><th class="money">金額</th></tr></thead><tbody>${items.length?items.map((x,i)=>`<tr><td>${i+1}. ${esc(x.description||'—')}</td><td>${esc(x.unit||'項')}</td><td>${n(x.quantity)}</td><td class="money">${hk(x.unit_price)}</td><td class="money">${hk(x.amount??n(x.quantity)*n(x.unit_price))}</td></tr>`).join(''):`<tr><td colspan="5" class="ub-blank">工程項目會即時顯示喺度</td></tr>`}</tbody></table>`};
formalSign=function(){return `<div class="ub-sign"><div><b>FOR AND BEHALF OF</b><div>UNIBRIGHT CONSTRUCTION (HK) LIMITED</div><div class="ub-sign-space"></div><div class="ub-sign-line">Authorized Signature</div></div><div><b>客戶簽署及確定</b><div class="ub-sign-space"></div><div class="ub-sign-line">Signature <span>Date</span></div></div></div>`};
payTable=function(){return `<table class="ub-pay"><thead><tr><th>收款方式</th><th>收款帳號</th></tr></thead><tbody><tr><td>銀行轉帳／支票</td><td>中國工商銀行（亞洲）有限公司 720502009151</td></tr><tr><td>轉數快 FPS</td><td>120437801</td></tr></tbody></table>`};
function ubFooter(){return `<div class="ub-footer">UNIBRIGHT CONSTRUCTION (H.K.) LIMITED</div>`}
quoteDocumentHTML=function(q,p,items,preview=false){const discountLabel=q.discount_type==='percent'&&q.discount_value?` (${q.discount_value}%)`:'';return `<article class="formal-document ub-a4" id="printArea">${formalHeader('報價單','QUOTATION')}<table class="ub-meta"><tr><td class="lab">報價單編號</td><td>${esc(q.quotation_no||'')}</td><td class="lab">工程編號</td><td>${esc(p.project_no||'')}</td></tr><tr><td class="lab">施工地點</td><td colspan="3">${esc(p.site_address||'—')}</td></tr><tr><td class="lab">聯絡人</td><td>${esc(p.contact_name||'')} ${esc(p.phone||'')}</td><td class="lab">報價日期</td><td>${esc(q.issue_date||today())}</td></tr><tr><td class="lab">客戶公司</td><td>${esc(p.company_name||'—')}</td><td class="lab">有效期至</td><td>${esc(q.valid_until||addDays(today(),90))}</td></tr><tr><td class="lab">電郵</td><td>${esc(p.email||'')}</td><td class="lab">客戶地址</td><td>${esc(p.client_address||'')}</td></tr></table><div class="ub-total-banner">HKD ${n(q.total).toLocaleString('en-HK',{minimumFractionDigits:2,maximumFractionDigits:2})}</div>${formalItems(items)}<table class="ub-summary"><tr><td>小計 Subtotal</td><td>${hk(q.subtotal)}</td></tr><tr><td>折扣 Discount${discountLabel}</td><td>- ${hk(q.discount_amount)}</td></tr><tr class="gold"><td>合計 Total</td><td>${hk(q.total)}</td></tr></table><div class="ub-note"><b>備註及付款條款</b><br>1. 收取訂金50%（HKD ${hk(n(q.total)*.5).replace('HK$','')}），完工7天內收取尾數。</div>${payTable()}${formalSign()}${ubFooter()}</article>`};
invoiceDocumentHTML=function(x,p,items,q,dp){const payable=n(x.total)*dp/100;return `<article class="formal-document ub-a4" id="printArea">${formalHeader('INVOICE','付款通知單')}<table class="ub-meta"><tr><td class="lab">Invoice No.</td><td>${esc(x.invoice_no||'PREVIEW-'+today().replaceAll('-',''))}</td><td class="lab">Invoice Date</td><td>${esc(x.issue_date||today())}</td></tr><tr><td class="lab">Ref. Quotation</td><td>${esc(q?.quotation_no||'')}</td><td class="lab">Project Ref.</td><td>${esc(p.project_no||'')}</td></tr><tr><td class="lab">BILL TO｜付款客戶</td><td>${esc(p.company_name||'—')}<br>${esc(p.client_address||'')}<br>${esc(p.email||'')}</td><td class="lab">PROJECT｜工程資料</td><td>${esc(p.project_name||'—')}<br>${esc(p.site_address||'')}<br>${esc(p.contact_name||'')} ${esc(p.phone||'')}</td></tr></table>${formalItems(items)}<table class="ub-summary"><tr><td>小計 Subtotal</td><td>${hk(x.subtotal)}</td></tr><tr><td>折扣 Discount</td><td>${hk(x.discount_amount)}</td></tr><tr><td>合約總額 Total</td><td>${hk(x.total)}</td></tr><tr class="gold"><td>本期應付 ${dp}% Deposit</td><td>${hk(payable)}</td></tr></table><div class="ub-note"><b>付款條款</b><br>收取訂金${dp}%（HKD ${hk(payable).replace('HK$','')}），完工7天內收取尾數。${x.due_date?` 到期日：${esc(x.due_date)}`:''}</div>${payTable()}${formalSign()}${ubFooter()}</article>`};
receiptDocumentHTML=function(pay,iv,p,cumulative,balance){return `<article class="formal-document ub-a4" id="printArea">${formalHeader('RECEIPT','收據')}<div class="ub-receipt-tag">收款確認</div><table class="ub-meta"><tr><td class="lab">Receipt No.</td><td>${esc(pay.receipt_no||'PREVIEW-'+today().replaceAll('-',''))}</td><td class="lab">Receipt Date</td><td>${esc(pay.payment_date||today())}</td></tr><tr><td class="lab">Ref. Invoice</td><td>${esc(iv.invoice_no||'')}</td><td class="lab">Project Ref.</td><td>${esc(p.project_no||'')}</td></tr><tr><td class="lab">BILL TO</td><td>${esc(p.company_name||'—')}<br>${esc(p.contact_name||'')}</td><td class="lab">PROJECT</td><td>${esc(p.project_name||'—')}<br>${esc(p.site_address||'')}</td></tr></table><table class="ub-items ub-receipt-items"><thead><tr><th class="desc">收款項目</th><th>付款方式</th><th>參考編號</th><th class="money">金額</th></tr></thead><tbody><tr><td>收取 Invoice ${esc(iv.invoice_no||'')} 款項</td><td>${esc(pay.method||'')}</td><td>${esc(pay.reference_no||'—')}</td><td class="money">${hk(pay.amount)}</td></tr></tbody></table><table class="ub-summary"><tr class="gold"><td>本次收款</td><td>${hk(pay.amount)}</td></tr><tr><td>累計已收</td><td>${hk(cumulative)}</td></tr><tr><td>尚欠</td><td>${hk(balance)}</td></tr></table><div class="ub-note"><b>備註：</b>${esc(pay.remarks||'—')}</div>${formalSign()}${ubFooter()}</article>`};
function fitFormalDocs(){requestAnimationFrame(()=>document.querySelectorAll('.preview-stage,.single-preview').forEach(stage=>{const paper=stage.querySelector('.formal-document');if(!paper)return;paper.style.transform='none';const w=stage.clientWidth||stage.parentElement?.clientWidth||794;const s=Math.min(1,Math.max(.28,(w-18)/794));paper.style.transform=`scale(${s})`;paper.style.transformOrigin='top left';stage.style.height=(1123*s+22)+'px'}))}
window.fitFormalDocs=fitFormalDocs;window.addEventListener('resize',fitFormalDocs);
const oq=updateQuotePreview;updateQuotePreview=function(){oq();fitFormalDocs()};
const oi=updateInvoicePreview;updateInvoicePreview=function(qid){oi(qid);fitFormalDocs()};
const orc=updateReceiptPreview;updateReceiptPreview=function(){orc();fitFormalDocs()};
const ovq=viewQuote;viewQuote=async function(id){await ovq(id);document.querySelectorAll('.view-actions .gold').forEach(b=>{b.onclick=printA4});fitFormalDocs()};
const ovi=viewInvoice;viewInvoice=async function(id){await ovi(id);document.querySelectorAll('.view-actions .gold').forEach(b=>{b.onclick=printA4});fitFormalDocs()};
const ovr=viewReceipt;viewReceipt=async function(id){await ovr(id);document.querySelectorAll('.view-actions .gold').forEach(b=>{b.onclick=printA4});fitFormalDocs()};
const nativePrint=window.print.bind(window);
window.printA4=function(){const paper=document.querySelector('.formal-document');if(!paper){nativePrint();return}const css=`@page{size:A4 portrait;margin:0}*{box-sizing:border-box}body{margin:0;background:white;font-family:Arial,'Microsoft JhengHei',sans-serif}.formal-document{width:210mm;min-height:297mm;padding:12mm 14mm 10mm;position:relative;color:#17231d;font-size:8.2pt;line-height:1.3}.ub-doc-head{display:grid;grid-template-columns:1fr auto;gap:10mm;align-items:start;border-bottom:.45mm solid #173f31;padding-bottom:3mm}.ub-doc-logo{width:42mm;height:auto}.ub-doc-title{text-align:right;color:#173f31}.ub-doc-title b{display:block;font-size:15pt}.ub-doc-title span{font-size:8pt}.ub-meta,.ub-items,.ub-pay,.ub-summary{border-collapse:collapse}.ub-meta{width:100%;margin-top:5mm}.ub-meta td{border:.2mm solid #d4dbd7;padding:2mm}.ub-meta .lab{font-weight:700;background:#fafbf9;width:26mm}.ub-total-banner{background:#173f31;color:white;text-align:right;font-size:18pt;font-weight:900;padding:3mm 4mm;margin:4mm 0}.ub-items{width:100%}.ub-items th{background:#173f31;color:white;text-align:left;padding:2.1mm;border:.2mm solid #173f31}.ub-items td{border:.2mm solid #d6ddd9;padding:2mm}.ub-items .money{text-align:right;white-space:nowrap}.ub-summary{width:80mm;margin:3mm 0 4mm auto}.ub-summary td{border:.2mm solid #d6ddd9;padding:2mm}.ub-summary td:last-child{text-align:right;font-weight:700}.ub-summary .gold td{background:#bd9849;color:white;font-weight:900;font-size:9.5pt}.ub-note{margin:4mm 0}.ub-pay{width:100%;margin-top:3mm}.ub-pay th{background:#173f31;color:white;text-align:left;padding:2mm}.ub-pay td{border:.2mm solid #d6ddd9;padding:2mm}.ub-sign{display:grid;grid-template-columns:1fr 1fr;gap:16mm;margin-top:9mm}.ub-sign-space{height:18mm}.ub-sign-line{border-top:.2mm solid #777;padding-top:1.5mm}.ub-sign-line span{float:right}.ub-footer{position:absolute;left:14mm;right:14mm;bottom:6mm;text-align:center;border-top:.2mm solid #d8ddda;padding-top:1.5mm;font-size:6.5pt;color:#98a19d}.ub-receipt-tag{display:inline-block;background:#173f31;color:#fff;padding:2mm 3mm;margin-top:4mm;font-weight:700}`;const w=window.open('','_blank');if(!w){document.querySelectorAll('.formal-document').forEach(x=>x.style.transform='none');nativePrint();return}w.document.open();w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>UNIBRIGHT Document</title><style>${css}</style></head><body>${paper.outerHTML}<script>setTimeout(()=>window.print(),350)<\/script></body></html>`);w.document.close()};
window.print=window.printA4;
setTimeout(fitFormalDocs,500);
})();