(()=>{'use strict';
window.UNIBRIGHT_BUILD='20260911-v18-clean-document-engine';
function visible(el){if(!el)return false;const r=el.getBoundingClientRect(),s=getComputedStyle(el);return s.display!=='none'&&s.visibility!=='hidden'&&r.width>250&&r.height>350}
function score(el){if(!el)return-1;let n=0;const c=String(el.className||''),t=(el.innerText||'').toUpperCase();if(c.includes('a4-sheet'))n+=100;if(c.includes('ub-a4'))n+=95;if(el.tagName==='ARTICLE')n+=40;if(/INVOICE|QUOTATION|RECEIPT|報價單|付款通知單|收據/.test(t))n+=60;if(el.querySelectorAll('table').length>=2)n+=30;if(visible(el))n+=50;const r=el.getBoundingClientRect();if(r.width>500&&r.height>700)n+=25;return n}
function findDoc(){const roots=[document.querySelector('.single-preview'),document.querySelector('.preview-stage'),document.getElementById('app'),document.body].filter(Boolean),sels=['.a4-sheet','.ub-a4','.a4-scale-box>article','.a4-scale-box>*','.preview-stage article','.single-preview article','article'];let list=[];for(const root of roots){for(const sel of sels){try{root.querySelectorAll(sel).forEach(x=>list.push(x))}catch(_){}}}return [...new Set(list)].filter(x=>score(x)>50).sort((a,b)=>score(b)-score(a))[0]||null}
function normalize(src){const c=src.cloneNode(true);if(!c.classList.contains('a4-sheet'))c.classList.add('a4-sheet');Object.assign(c.style,{transform:'none',transformOrigin:'top left',margin:'0',boxShadow:'none',width:'794px',height:'1123px',minHeight:'1123px',maxHeight:'1123px',overflow:'hidden',background:'#fff',position:'relative'});return c}
function filename(){const src=findDoc(),txt=src?.innerText||document.body.innerText||'',title=/RECEIPT|收據/i.test(txt)?'Receipt':/INVOICE|付款通知單/i.test(txt)?'Invoice':'Quotation',no=txt.match(/(?:QO|TQ|INV|RCP|RC)[A-Z0-9\/-]*/i)?.[0]||new Date().toISOString().slice(0,10);return `UNIBRIGHT_${title}_${String(no).replace(/[\\/:*?"<>|]+/g,'-')}.pdf`}
async function exactBlob(){const src=findDoc();if(!src)throw new Error('畫面上搵唔到正式 A4 文件');if(!window.html2canvas)throw new Error('html2canvas 未載入');if(!(window.jspdf&&window.jspdf.jsPDF))throw new Error('jsPDF 未載入');if(document.fonts?.ready)await document.fonts.ready;const clone=normalize(src),host=document.createElement('div');host.style.cssText='position:fixed;left:-10000px;top:0;width:794px;height:1123px;overflow:hidden;background:#fff;z-index:-1;pointer-events:none';host.appendChild(clone);document.body.appendChild(host);try{await Promise.all([...clone.querySelectorAll('img')].map(async im=>{try{if(im.decode)await im.decode()}catch(_){}}));await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const canvas=await window.html2canvas(clone,{backgroundColor:'#fff',scale:2,useCORS:true,allowTaint:true,logging:false,width:794,height:1123,windowWidth:794,windowHeight:1123,scrollX:0,scrollY:0,x:0,y:0});if(!canvas||canvas.width!==1588||canvas.height!==2246)throw new Error(`A4 畫布尺寸錯誤 ${canvas?.width||0}×${canvas?.height||0}`);const {jsPDF}=window.jspdf,pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true,putOnlyUsedFonts:true});pdf.addImage(canvas.toDataURL('image/jpeg',0.985),'JPEG',0,0,210,297,undefined,'FAST');if(pdf.getNumberOfPages()!==1)throw new Error('PDF 頁數唔係 1');const blob=pdf.output('blob');if(!blob||blob.size<5000)throw new Error('PDF 檔案建立失敗');return blob}finally{host.remove()}}
let busy=false;
window.downloadCurrentPDF=window.exportCurrentPDF=async function(name){if(busy)return false;busy=true;const isMobile=/iPhone|iPad|iPod|Android/i.test(navigator.userAgent);let popup=null;try{if(isMobile){popup=window.open('about:blank','_blank');if(!popup)throw new Error('瀏覽器阻止咗 PDF 視窗');popup.document.write('<meta name="viewport" content="width=device-width"><p style="font:16px sans-serif;padding:24px">正在建立 A4 PDF…</p>')}const blob=await exactBlob(),fn=name||filename(),url=URL.createObjectURL(blob);if(isMobile){popup.location.replace(url)}else{const a=document.createElement('a');a.href=url;a.download=fn;document.body.appendChild(a);a.click();a.remove()}setTimeout(()=>URL.revokeObjectURL(url),300000);return true}catch(e){try{popup?.close()}catch(_){}console.error('V18 PDF',e);alert('PDF 下載失敗：'+String(e?.message||e));return false}finally{busy=false}};
window.printCurrentA4=window.printA4=function(){const src=findDoc();if(!src){alert('畫面上搵唔到正式 A4 文件');return false}const html=normalize(src).outerHTML,w=window.open('about:blank','_blank');if(!w){alert('瀏覽器阻止咗列印視窗');return false}w.document.open();w.document.write(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zoechow412-ui/m@f5f55fb1b62550121a2053b213d4248ed31a028f/unibright-ops/v15/a4-approved.css"><style>html,body{margin:0!important;padding:0!important;width:210mm!important;height:297mm!important;overflow:hidden!important;background:#fff!important}.a4-sheet{width:210mm!important;height:297mm!important;min-height:297mm!important;max-height:297mm!important;margin:0!important;padding:9.5mm 11.6mm 7.5mm!important;box-shadow:none!important;transform:none!important;overflow:hidden!important;box-sizing:border-box!important}@page{size:A4 portrait;margin:0}</style></head><body>${html}<script>window.onload=()=>setTimeout(()=>{window.focus();window.print()},500)<\/script></body></html>`);w.document.close();return true};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const t=(b.textContent||'').replace(/\s+/g,' ').trim();if(t==='下載 PDF'||t==='下載／儲存 PDF'||t==='下載 / 儲存 PDF'){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();window.downloadCurrentPDF();return}if(t==='列印'){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();window.printCurrentA4();}},true);
window.UNIBRIGHT_V18=()=>{const d=findDoc();return{build:window.UNIBRIGHT_BUILD,doc:!!d,score:score(d),canvas:!!window.html2canvas,jspdf:!!window.jspdf?.jsPDF,pdf:typeof window.downloadCurrentPDF==='function',print:typeof window.printCurrentA4==='function'}};
})();