(()=>{
'use strict';
window.UNIBRIGHT_STABLE_BUILD='20260912-v24-stable-actions-r2';
function addTheme(){if(document.getElementById('ub-v24-theme'))return;const s=document.createElement('style');s.id='ub-v24-theme';s.textContent=`
:root{--ub-navy:#0b2c5b;--ub-green:#0a2e1f;--ub-gold:#c7a45c;--ub-line:#e4e9ec;--ub-soft:#f7f9fa;--ub-danger:#a62c2b}
html,body{background:#fff!important}.workspace,.content{background:#fff!important}.sidebar{background:#fff!important;border-right:1px solid var(--ub-line)!important}.topbar{background:#fff!important;border-bottom:1px solid var(--ub-line)!important}.card,.project-card,.document-card,.form-card,.step-card,.preview-pane,.editor-pane{background:#fff!important}.hero{background:#fff!important;border:1px solid var(--ub-line)!important}.hero h1,.page-head h1,.card h2,.card h3{color:var(--ub-navy)!important}.side-nav button.active{background:#eef4f8!important;color:var(--ub-navy)!important}.mobile-nav{background:#fff!important;border-top:1px solid var(--ub-line)!important}.ub-quickbar{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:10px;margin:14px 0 18px}.ub-quickbar button{border:1px solid var(--ub-line);background:#fff;border-radius:14px;padding:12px 10px;font-weight:800;color:var(--ub-navy);box-shadow:0 5px 16px rgba(11,44,91,.05);cursor:pointer}.ub-quickbar button small{display:block;margin-top:4px;color:#7a8c9e;font-weight:600}.ub-db-pill{display:inline-flex;align-items:center;gap:6px;padding:7px 10px;border:1px solid #dce6e2;border-radius:999px;background:#f7fbf9;color:var(--ub-green);font-size:11px;font-weight:800}.ub-db-dot{width:8px;height:8px;border-radius:50%;background:#2f8f66}.ub-project-actions{display:flex;gap:8px;align-items:center;justify-content:flex-end;flex-wrap:wrap}.ub-delete-btn{border:1px solid #eccccc!important;background:#fff!important;color:var(--ub-danger)!important}.ub-delete-btn:hover{background:#fff6f6!important}.ub-stable-note{font-size:11px;color:#7a8c9e;margin-top:8px}@media(max-width:900px){.ub-quickbar{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.ub-quickbar{grid-template-columns:repeat(2,1fr)}.ub-quickbar button{padding:11px 8px;font-size:12px}.ub-project-actions{justify-content:flex-start}}
`;document.head.appendChild(s)}
function addDbPill(){const bar=document.querySelector('.topbar');if(!bar||bar.querySelector('.ub-db-pill'))return;const d=document.createElement('div');d.className='ub-db-pill';d.innerHTML='<span class="ub-db-dot"></span>Supabase 已連線';bar.appendChild(d)}
function addQuickbar(){if(typeof app==='undefined'||!app||document.querySelector('.ub-quickbar'))return;const hero=app.querySelector('.hero');if(!hero)return;const q=document.createElement('div');q.className='ub-quickbar';q.innerHTML=`<button onclick="newQuote()">＋ 新報價<small>客戶／同行</small></button><button onclick="setNav('invoice')">Invoice<small>查看應收款</small></button><button onclick="setNav('receipt')">收款／Receipt<small>登記及下載</small></button><button onclick="setNav('pricing')">價目表<small>直接改價</small></button><button onclick="setNav('pricing')">改價紀錄<small>舊價 → 新價</small></button>`;hero.insertAdjacentElement('afterend',q)}
addTheme();addDbPill();setTimeout(addQuickbar,400);
const originalRenderDashboard=window.renderDashboard;
if(typeof originalRenderDashboard==='function')window.renderDashboard=function(){originalRenderDashboard();addQuickbar();addDbPill()};
window.renderProjects=function(){const list=filteredProjects();app.innerHTML=`<div class="page-head"><div><h1>工程項目</h1><p>工程資料、客戶資料、進度同收款放埋一齊。新工程由新報價建立。</p></div></div><div class="stack">${list.map((p,i)=>{const s=sumProject(p.id),c=clientByProject(p.id);return `<div class="project-card"><div class="thumb thumb-${i%3+1}"></div><div><h3>${esc(p.project_name)}</h3><p>${esc(p.project_no)} · ${esc(p.site_address||'')}</p><p>${esc(c.company_name||'')} ${esc(c.contact_name||'')}</p><div class="finance"><span>進度<b>${n(p.progress_percent)}%</b></span><span>合約額<b>${hk(p.contract_amount)}</b></span><span>已收<b>${hk(s.received_amount)}</b></span><span>尚欠<b>${hk(s.outstanding_amount??p.contract_amount)}</b></span></div></div><div class="ub-project-actions"><button class="btn light" onclick="editProject('${p.id}')">編輯項目</button><button class="btn light ub-delete-btn" onclick="deleteProject('${p.id}')">刪除項目</button></div></div>`}).join('')||'<div class="empty-state">未有工程項目。</div>'}</div>`};
window.deleteProject=async function(id){const p=D.projects.find(x=>x.id===id);if(!p){toast('搵唔到工程項目');return}const name=p.project_name||p.project_no||'此工程';const ok=window.confirm(`確定刪除「${name}」？\n\n會一併刪除此工程相關嘅報價單、Invoice、收款／Receipt 同進度紀錄。呢個動作不能復原。`);if(!ok)return;try{await api('projects','?id=eq.'+encodeURIComponent(id),{method:'DELETE'});toast('工程項目已刪除');await refreshData();tab='projects';renderProjects()}catch(e){alert('刪除工程失敗：'+String(e?.message||e))}};
window.saveQuote=async function(){const clean=draft.filter(x=>String(x.description||'').trim()&&n(x.quantity)>0);if(!clean.length){toast('請加入至少一個工程項目');return}try{const pid=val('qproject')==='NEW'?await createProjectFromQuote():val('qproject');const c=quoteTotals();const no=gen(tier==='trade'?'TQ':'QO');const q=await api('quotations','',{method:'POST',body:{quotation_no:no,project_id:pid,issue_date:today(),valid_until:addDays(today(),90),discount_type:c.type,discount_value:c.v,subtotal:c.s,discount_amount:c.d,total:c.t,status:'草稿',price_tier:tier}});if(clean.length)await api('quotation_items','',{method:'POST',body:clean.map((x,i)=>({quotation_id:q[0].id,sort_order:i+1,description:x.description,unit:x.unit,quantity:x.quantity,unit_price:x.unit_price}))});toast('報價已永久儲存');await refreshData();await viewQuote(q[0].id)}catch(e){alert('儲存報價失敗：'+String(e?.message||e))}};
window.saveInvoice=async function(qid){try{const existing=D.invoices.find(x=>x.quotation_id===qid);if(existing){toast('呢張報價已經有 Invoice');await viewInvoice(existing.id);return}const ctx=window.__invoiceContext;if(!ctx)throw new Error('Invoice 資料未載入');const dp=Math.max(0,Math.min(100,n(val('invDeposit')||50)));const no=gen('INV');const iv=await api('invoices','',{method:'POST',body:{invoice_no:no,project_id:ctx.q.project_id,quotation_id:qid,issue_date:val('invDate')||today(),due_date:val('invDue')||addDays(today(),7),subtotal:ctx.q.subtotal,discount_amount:ctx.q.discount_amount,total:ctx.q.total,amount_paid:0,status:'未付款',notes:'DEPOSIT_PERCENT='+dp+'; '+val('invNote')}});if(ctx.items.length)await api('invoice_items','',{method:'POST',body:ctx.items.map((x,i)=>({invoice_id:iv[0].id,sort_order:i+1,description:x.description,unit:x.unit,quantity:x.quantity,unit_price:x.unit_price}))});await api('quotations','?id=eq.'+qid,{method:'PATCH',body:{status:'已轉Invoice'}});try{await api('projects','?id=eq.'+ctx.q.project_id,{method:'PATCH',body:{contract_amount:ctx.q.total}})}catch(_){}toast('Invoice 已永久儲存');await refreshData();await viewInvoice(iv[0].id)}catch(e){alert('建立 Invoice 失敗：'+String(e?.message||e))}};
window.savePayment=async function(id){const ctx=window.__paymentContext;let x=ctx?.x||D.invoices.find(v=>v.id===id);const a=n(val('payAmount'));if(!x){toast('搵唔到 Invoice');return}if(a<=0||a>n(x.amount_due)+.01){toast('收款金額不正確');return}try{const rno=gen('RCP');const rows=await api('payments','',{method:'POST',body:{project_id:x.project_id,invoice_id:id,receipt_no:rno,payment_date:val('payDate')||today(),amount:a,method:val('payMethod')||'FPS 轉數快',reference_no:val('payRef').trim(),remarks:val('payRemarks').trim()}});toast('收款已永久儲存，Receipt 已生成');await refreshData();if(rows[0]?.id)await viewReceipt(rows[0].id);else setNav('receipt')}catch(e){alert('收款失敗：'+String(e?.message||e))}};
window.UNIBRIGHT_HEALTH=()=>({stable:window.UNIBRIGHT_STABLE_BUILD,supabase:true,deleteProject:typeof window.deleteProject==='function',saveQuote:typeof window.saveQuote==='function',saveInvoice:typeof window.saveInvoice==='function',savePayment:typeof window.savePayment==='function',pdf:typeof window.exportCurrentPDF==='function',pricing:typeof window.saveCatalogPrice==='function'});
})();