const BASE='https://bkjrzksoruhlzwrzpovw.supabase.co';
const KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJranJ6a3NvcnVobHp3cnpwb3Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY3Nzc2ODQsImV4cCI6MjEwMjM1MzY4NH0.RSoUlsO1ae8M6O7X62BgF42CnV2kMW7NtYR3ez1pPWU';
const HEAD={apikey:KEY,Authorization:'Bearer '+KEY,'Content-Type':'application/json'};
let D={projects:[],summary:[],clients:[],quotes:[],invoices:[],payments:[],pricing:[]};
let tab='dashboard',tier='customer',draft=[];
const app=document.getElementById('app'),toastEl=document.getElementById('toast');
const n=v=>Number(v||0),hk=v=>'HK$'+n(v).toLocaleString('en-HK',{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
const gen=p=>p+'/'+today().replaceAll('-','').slice(2)+'/'+String(Date.now()).slice(-5);
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2200)}
async function api(table,q='',o={}){const r=await fetch(BASE+'/rest/v1/'+table+q,{method:o.method||'GET',headers:{...HEAD,Prefer:o.prefer||'return=representation'},body:o.body?JSON.stringify(o.body):undefined});const t=await r.text();if(!r.ok)throw new Error(t||('HTTP '+r.status));return t?JSON.parse(t):[]}
async function load(){app.innerHTML='<div class="card">正在載入工程資料…</div>';try{const [projects,summary,clients,quotes,invoices,payments,pricing]=await Promise.all([api('projects','?select=*&order=created_at.desc'),api('project_financial_summary','?select=*'),api('clients','?select=*'),api('quotations','?select=*&order=created_at.desc'),api('invoices','?select=*&order=created_at.desc'),api('payments','?select=*&order=payment_date.desc,created_at.desc'),api('pricing_catalog','?select=*&active=eq.true&order=price_tier,item_code')]);D={projects,summary,clients,quotes,invoices,payments,pricing};render()}catch(e){app.innerHTML='<div class="card"><h3>資料庫連線失敗</h3><p>'+esc(e.message)+'</p><button class="btn" onclick="load()">重新載入</button></div>'}}
function project(id){return D.projects.find(x=>x.id===id)}
function sumProject(id){return D.summary.find(x=>x.project_id===id)||{}}
function clientByProject(id){const p=project(id);return D.clients.find(x=>x.id===p?.client_id)||{}}
function setNav(t){tab=t;document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===t));render()}
document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.nav)setNav(b.dataset.nav)}));
const globalSearch=document.getElementById('globalSearch');globalSearch.addEventListener('input',()=>{if(tab==='dashboard'||tab==='projects')render()});
function render(){({dashboard:renderDashboard,projects:renderProjects,quotation:renderQuotes,invoice:renderInvoices,receipt:renderReceipts,pricing:renderPricing}[tab]||renderDashboard)()}
function filteredProjects(){const q=(globalSearch.value||'').trim().toLowerCase();if(!q)return D.projects;return D.projects.filter(p=>[p.project_no,p.project_name,p.site_address,clientByProject(p.id).company_name].join(' ').toLowerCase().includes(q))}
function renderDashboard(){const projects=filteredProjects();const pendingQuotes=D.quotes.filter(q=>q.status!=='已轉Invoice'&&q.status!=='已接受').length;const dueInv=D.invoices.filter(x=>n(x.amount_due)>0).length;const received=D.payments.reduce((a,x)=>a+n(x.amount),0);const contract=D.summary.reduce((a,x)=>a+n(x.contract_amount),0);const due=Math.max(0,contract-received);const paidPct=contract?Math.min(100,Math.round(received/contract*100)):0;const duePct=contract?Math.min(100-paidPct,Math.round(due/contract*100)):0;const upcoming=Math.max(0,100-paidPct-duePct);const top=projects.slice(0,3);app.innerHTML=`<section class="hero"><div class="hero-copy"><h1>Welcome<span>!</span></h1><p>今日工程進度・報價・收款，一眼睇晒。</p></div><div class="hero-visual"></div></section><section class="kpis"><div class="kpi yellow" onclick="newQuote()"><div class="bubble">＋</div><div><small>新報價單</small><strong>${D.quotes.length}</strong></div><div class="arrow">›</div></div><div class="kpi blue" onclick="setNav('quotation')"><div class="bubble">▤</div><div><small>待處理報價</small><strong>${pendingQuotes}</strong></div><div class="arrow">›</div></div><div class="kpi pink" onclick="setNav('invoice')"><div class="bubble">$</div><div><small>待收款 Invoice</small><strong>${dueInv}</strong></div><div class="arrow">›</div></div><div class="kpi mint" onclick="setNav('receipt')"><div class="bubble">✓</div><div><small>Receipt 收據</small><strong>${D.payments.length}</strong></div><div class="arrow">›</div></div></section><section class="dashboard-grid"><div class="dash-col"><div class="card"><div class="card-head"><h2>My Projects｜工程項目</h2><button class="card-link" onclick="setNav('projects')">›</button></div><div class="project-list">${top.length?top.map(projectRow).join(''):'<p class="muted">未有工程項目。</p>'}</div></div><div class="card"><div class="card-head"><h3>工程時間表 (Project Timeline)</h3><button class="card-link" onclick="setNav('projects')">›</button></div>${timelineHTML(top)}</div></div><div class="dash-col"><div class="card"><div class="card-head"><h3>收款進度</h3></div><div class="donut-wrap"><div class="donut" style="--paid:${paidPct};--due:${duePct}"><div class="donut-center"><b>${paidPct}%</b><span>已收款</span></div></div><div class="legend"><div><i class="paid"></i>已收 ${hk(received)}</div><div><i class="due"></i>待收 ${hk(due)}</div><div><i class="up"></i>即將到期 ${upcoming}%</div></div></div></div><div class="card"><div class="card-head"><h3>最近活動</h3><button class="card-link" onclick="setNav('quotation')">›</button></div><div class="activity-list">${recentHTML()}</div></div></div></section>`}
function projectRow(p,i=0){const s=sumProject(p.id);return `<div class="project-row"><div class="project-thumb"></div><div class="project-main"><b>${esc(p.project_name||'未命名工程')}</b><div class="project-sub">${esc(p.project_no||'')} · ${esc(p.status||'')}</div><div class="progress-row"><div class="bar"><i style="width:${Math.min(100,n(p.progress_percent))}%"></i></div><span class="pct">${n(p.progress_percent)}%</span></div></div><button class="circle-btn" onclick="editProject('${p.id}')">›</button></div>`}
function timelineHTML(list){if(!list.length)return'<p class="muted">未有工程時間表。</p>';const months=['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'];return `<div class="months">${months.map(x=>'<span>'+x+'</span>').join('')}</div>${list.map((p,i)=>`<div class="timeline-row"><div class="timeline-name">${esc(p.project_name)}</div><div class="timeline-track"><i style="width:${Math.max(18,Math.min(55,n(p.progress_percent)||25))}%"></i></div></div>`).join('')}`}
function recentHTML(){const a=[];D.quotes.slice(0,2).forEach(x=>a.push({ico:'＋',t:'新增報價單',s:x.quotation_no,time:x.created_at}));D.invoices.slice(0,2).forEach(x=>a.push({ico:'$',t:'Invoice 已發出',s:x.invoice_no,time:x.created_at}));D.payments.slice(0,2).forEach(x=>a.push({ico:'✓',t:'收到款項',s:x.receipt_no||hk(x.amount),time:x.created_at||x.payment_date}));a.sort((x,y)=>new Date(y.time||0)-new Date(x.time||0));return (a.slice(0,4).map(x=>`<div class="activity"><div class="activity-ico">${x.ico}</div><div><b>${esc(x.t)}</b><small>${esc(x.s)}</small></div><small>${relativeTime(x.time)}</small></div>`).join('')||'<p class="muted">未有活動。</p>')}
function relativeTime(v){if(!v)return'';const d=Math.max(0,Date.now()-new Date(v).getTime()),h=Math.floor(d/3600000);if(h<1)return'剛剛';if(h<24)return h+'小時前';return Math.floor(h/24)+'日前'}
function renderProjects(){const list=filteredProjects();app.innerHTML=`<div class="page-head"><div><h1>工程項目</h1><p>查看工程進度、合約額、已收及尚欠。</p></div><button class="btn" onclick="newProject()">＋ 新工程</button></div><div class="stack">${list.map(p=>{const s=sumProject(p.id),c=clientByProject(p.id);return `<div class="project-card"><div class="thumb"></div><div><h3>${esc(p.project_name)}</h3><p>${esc(p.project_no)} · ${esc(p.site_address||'')}</p><p>${esc(c.company_name||'')} ${esc(c.contact_name||'')}</p><div class="finance"><span>進度<b>${n(p.progress_percent)}%</b></span><span>合約額<b>${hk(p.contract_amount)}</b></span><span>已收<b>${hk(s.received_amount)}</b></span><span>尚欠<b>${hk(s.outstanding_amount??p.contract_amount)}</b></span></div></div><button class="btn light" onclick="editProject('${p.id}')">編輯項目</button></div>`}).join('')||'<div class="card">未有工程項目。</div>'}</div>`}
function newProject(){showProjectForm(null)}
function editProject(id){showProjectForm(project(id))}
function showProjectForm(p){const c=p?clientByProject(p.id):{};app.innerHTML=`<div class="page-head"><div><h1>${p?'編輯項目':'建立新工程'}</h1><p>工程資料同客戶資料可以一次過更新。</p></div><button class="btn light" onclick="setNav('projects')">返回</button></div><div class="form-card"><div class="form-grid"><div class="field"><label>工程／項目名稱</label><input id="epname" value="${esc(p?.project_name||'')}"></div><div class="field"><label>工程編號</label><input id="epno" value="${esc(p?.project_no||('UB-'+today().replaceAll('-','')+'-'+String(Date.now()).slice(-4)))}"></div><div class="field full"><label>施工地址</label><textarea id="esite">${esc(p?.site_address||'')}</textarea></div><div class="field"><label>狀態</label><select id="estatus">${['報價中','已確認','施工中','待收款','已完成'].map(x=>`<option ${p?.status===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>工程進度 %</label><input id="eprogress" type="number" min="0" max="100" value="${n(p?.progress_percent)}"></div><div class="field"><label>合約金額</label><input id="econtract" type="number" min="0" value="${n(p?.contract_amount)}"></div><div class="field"><label>客戶／公司名稱</label><input id="ecname" value="${esc(c.company_name||'')}"></div><div class="field"><label>聯絡人</label><input id="econtact" value="${esc(c.contact_name||'')}"></div><div class="field"><label>電話</label><input id="ephone" value="${esc(c.phone||'')}"></div><div class="field"><label>Email</label><input id="eemail" value="${esc(c.email||'')}"></div><div class="field full"><label>客戶地址</label><textarea id="ecaddr">${esc(c.address||'')}</textarea></div></div><div class="form-actions"><button class="btn light" onclick="setNav('projects')">取消</button><button class="btn green" onclick="saveProject('${p?.id||''}','${c.id||''}')">儲存</button></div></div>`}
async function saveProject(pid,cid){if(!epname.value.trim()){toast('請輸入工程名稱');return}try{let clientId=cid;if(clientId){await api('clients','?id=eq.'+clientId,{method:'PATCH',body:{company_name:ecname.value.trim(),contact_name:econtact.value.trim(),phone:ephone.value.trim(),email:eemail.value.trim(),address:ecaddr.value.trim()}})}else{const cc=await api('clients','',{method:'POST',body:{company_name:ecname.value.trim()||'未命名客戶',contact_name:econtact.value.trim(),phone:ephone.value.trim(),email:eemail.value.trim(),address:ecaddr.value.trim()}});clientId=cc[0].id}const body={project_no:epno.value.trim(),client_id:clientId,project_name:epname.value.trim(),site_address:esite.value.trim(),status:estatus.value,progress_percent:Math.max(0,Math.min(100,n(eprogress.value))),contract_amount:n(econtract.value)};if(pid){await api('projects','?id=eq.'+pid,{method:'PATCH',body});await api('project_progress','',{method:'POST',body:{project_id:pid,progress_percent:body.progress_percent,status:body.status,update_note:'更新工程資料'}})}else await api('projects','',{method:'POST',body});toast('已儲存工程');await load();tab='projects';render()}catch(e){alert('儲存失敗：'+e.message)}}
function renderQuotes(){app.innerHTML=`<div class="page-head"><div><h1>報價單</h1><p>客戶價同同行價分開管理。</p></div><button class="btn" onclick="newQuote()">＋ 新報價</button></div><div class="card"><div style="overflow:auto"><table class="data-table"><thead><tr><th>報價編號</th><th>類別</th><th>日期</th><th>狀態</th><th>總額</th><th></th></tr></thead><tbody>${D.quotes.map(q=>`<tr><td>${esc(q.quotation_no)}</td><td>${q.price_tier==='trade'?'同行價':'客戶價'}</td><td>${esc(q.issue_date||'')}</td><td>${esc(q.status||'')}</td><td>${hk(q.total)}</td><td><button class="btn sm light" onclick="viewQuote('${q.id}')">正式報價單</button> ${q.status!=='已轉Invoice'?`<button class="btn sm green" onclick="convertForm('${q.id}')">轉 Invoice</button>`:''}</td></tr>`).join('')}</tbody></table></div></div>`}
function newQuote(){tier='customer';draft=[];renderQuoteEditor()}
function renderQuoteEditor(){app.innerHTML=`<div class="page-head"><div><h1>建立報價</h1><p>先揀客戶價／同行價，再加入工程項目。</p></div><button class="btn light" onclick="setNav('quotation')">返回</button></div><div class="form-card"><div class="segmented"><button id="tierCustomer" class="${tier==='customer'?'on':''}" onclick="setTier('customer')">客戶價</button><button id="tierTrade" class="${tier==='trade'?'on':''}" onclick="setTier('trade')">同行價</button></div><div class="section-label" style="margin-top:16px;font-weight:900">工程／項目</div><div class="field"><select id="qproject" onchange="projectChoiceChanged()"><option value="NEW">＋ 新工程／自行輸入名稱</option>${D.projects.map(p=>`<option value="${p.id}">${esc(p.project_no)}｜${esc(p.project_name)}</option>`).join('')}</select></div><div id="newProjectBox">${newProjectQuoteFields()}</div><div id="existingProjectBox" class="hidden"></div><div class="quote-grid" style="margin-top:16px"><div><div class="card-head"><h3>${tier==='trade'?'同行合作價目':'客戶標準價目'}</h3></div><div id="catalog" class="catalog"></div></div><div><div class="field"><label>折扣方式</label><select id="dtype" onchange="calcQuote()"><option value="percent">百分比 %</option><option value="fixed">固定金額 HK$</option></select></div><div class="field"><label>折扣數值</label><input id="dval" type="number" value="0" min="0" oninput="calcQuote()"></div>${tier==='customer'?`<div class="field"><label>房數</label><input id="rooms" type="number" min="1" value="3"></div><div class="plan-row"><button class="plan-chip" onclick="applyPlan(1)">PLAN 1 輕微整改</button><button class="plan-chip" onclick="applyPlan(2)">PLAN 2 中度整改</button><button class="plan-chip" onclick="applyPlan(3)">PLAN 3 大改重整</button></div>`:''}</div></div><div id="quoteItems"></div><div class="form-actions"><button class="btn light" onclick="addBlankItem()">＋ 自訂項目</button></div><div class="totals"><div><span>小計</span><b id="qsub">HK$0.00</b></div><div><span>折扣</span><b id="qdisc">HK$0.00</b></div><div class="grand"><span>總額</span><b id="qtotal">HK$0.00</b></div></div><div class="form-actions"><button class="btn green" onclick="saveQuote()">儲存報價</button></div></div>`;drawCatalog();drawQuoteItems()}
function newProjectQuoteFields(){return `<div class="form-grid" style="margin-top:12px"><div class="field"><label>工程／項目名稱</label><input id="npname" placeholder="直接輸入工程名稱"></div><div class="field"><label>工程編號</label><input id="npno" value="UB-${today().replaceAll('-','')}-${String(Date.now()).slice(-4)}"></div><div class="field full"><label>施工地址</label><textarea id="nsite" placeholder="直接輸入施工地址"></textarea></div><div class="field"><label>客戶／公司名稱</label><input id="ncname"></div><div class="field"><label>聯絡人</label><input id="ncontact"></div><div class="field"><label>電話</label><input id="nphone"></div><div class="field"><label>Email</label><input id="nemail"></div><div class="field full"><label>客戶地址</label><textarea id="ncaddr"></textarea></div></div>`}
function projectChoiceChanged(){const v=qproject.value;newProjectBox.classList.toggle('hidden',v!=='NEW');existingProjectBox.classList.toggle('hidden',v==='NEW');if(v!=='NEW'){const p=project(v),c=clientByProject(v);existingProjectBox.innerHTML=`<div class="card" style="margin-top:12px"><b>${esc(p.project_name)}</b><p style="margin:6px 0;color:#72839c">${esc(p.site_address||'')}</p><small>${esc(c.company_name||'')} · ${esc(c.contact_name||'')} · ${esc(c.phone||'')}</small></div>`}}
function setTier(t){tier=t;draft=[];renderQuoteEditor()}
function drawCatalog(){const el=document.getElementById('catalog');if(!el)return;const list=D.pricing.filter(x=>x.price_tier===tier);el.innerHTML=list.map(x=>`<div class="catalog-item"><div><b>${esc(x.description)}</b><small>${hk(x.unit_price)}／${esc(x.unit)}${x.pricing_rule?' · '+esc(x.pricing_rule):''}</small></div><button class="btn sm" onclick="pickItem('${x.item_code}')">加入</button></div>`).join('')||'<p style="padding:12px">未有價目。</p>'}
function pickItem(code){const x=D.pricing.find(v=>v.item_code===code);if(!x)return;draft.push({description:x.description,unit:x.unit,quantity:1,unit_price:n(x.unit_price)});drawQuoteItems()}
function addBlankItem(){draft.push({description:'',unit:'項',quantity:1,unit_price:0});drawQuoteItems()}
function changeQty(i,d){draft[i].quantity=Math.max(0,n(draft[i].quantity)+d);drawQuoteItems()}
function removeItem(i){draft.splice(i,1);drawQuoteItems()}
function drawQuoteItems(){const el=document.getElementById('quoteItems');if(!el)return;el.innerHTML=`<div class="quote-items"><table><thead><tr><th>工程項目</th><th>單位</th><th>數量</th><th>單價</th><th>小計</th><th></th></tr></thead><tbody>${draft.map((x,i)=>`<tr><td><input value="${esc(x.description)}" oninput="draft[${i}].description=this.value"></td><td><input value="${esc(x.unit)}" oninput="draft[${i}].unit=this.value"></td><td><div class="qty"><button onclick="changeQty(${i},-1)">−</button><input type="number" min="0" value="${x.quantity}" oninput="draft[${i}].quantity=n(this.value);calcQuote()"><button onclick="changeQty(${i},1)">＋</button></div></td><td><input type="number" min="0" value="${x.unit_price}" oninput="draft[${i}].unit_price=n(this.value);calcQuote()"></td><td id="line${i}">${hk(n(x.quantity)*n(x.unit_price))}</td><td><button class="btn sm red" onclick="removeItem(${i})">刪除</button></td></tr>`).join('')||'<tr><td colspan="6">未加入工程項目。</td></tr>'}</tbody></table></div>`;calcQuote()}
function calcQuote(){const s=draft.reduce((a,x)=>a+n(x.quantity)*n(x.unit_price),0);const type=document.getElementById('dtype')?.value||'percent',v=n(document.getElementById('dval')?.value),d=type==='fixed'?Math.min(s,v):s*v/100,t=Math.max(0,s-d);draft.forEach((x,i)=>{const e=document.getElementById('line'+i);if(e)e.textContent=hk(n(x.quantity)*n(x.unit_price))});if(document.getElementById('qsub')){qsub.textContent=hk(s);qdisc.textContent=hk(d);qtotal.textContent=hk(t)}return{s,d,t,type,v}}
function planQty(code,rooms){if(['CUS-04','CUS-06'].includes(code))return rooms+1;if(['CUS-05','CUS-09','CUS-16'].includes(code))return 1;return rooms}
function applyPlan(plan){const rooms=Math.max(1,n(document.getElementById('rooms').value||3)),max=plan===1?7:plan===2?12:18,list=D.pricing.filter(x=>x.price_tier==='customer'&&Number(String(x.item_code).split('-')[1])<=max);draft=list.map(x=>({description:x.description,unit:x.unit,quantity:planQty(x.item_code,rooms),unit_price:n(x.unit_price)}));drawQuoteItems()}
async function createProjectFromQuote(){if(!npname.value.trim())throw new Error('請輸入工程／項目名稱');const c=await api('clients','',{method:'POST',body:{company_name:ncname.value.trim()||'未命名客戶',contact_name:ncontact.value.trim(),phone:nphone.value.trim(),email:nemail.value.trim(),address:ncaddr.value.trim()}});const p=await api('projects','',{method:'POST',body:{project_no:npno.value.trim()||gen('PRJ'),client_id:c[0].id,project_name:npname.value.trim(),site_address:nsite.value.trim(),status:'報價中',progress_percent:0,contract_amount:0}});return p[0].id}
async function saveQuote(){const clean=draft.filter(x=>x.description.trim()&&n(x.quantity)>0);if(!clean.length){toast('請加入至少一個工程項目');return}try{const pid=qproject.value==='NEW'?await createProjectFromQuote():qproject.value;const c=calcQuote(),no=gen(tier==='trade'?'TQ':'QO');const q=await api('quotations','',{method:'POST',body:{quotation_no:no,project_id:pid,issue_date:today(),valid_until:new Date(Date.now()+90*86400000).toISOString().slice(0,10),discount_type:c.type,discount_value:c.v,subtotal:c.s,discount_amount:c.d,total:c.t,status:'草稿',price_tier:tier}});await api('quotation_items','',{method:'POST',body:clean.map((x,i)=>({quotation_id:q[0].id,sort_order:i+1,description:x.description,unit:x.unit,quantity:x.quantity,unit_price:x.unit_price,amount:n(x.quantity)*n(x.unit_price)}))});toast('報價已儲存');await load();tab='quotation';render()}catch(e){alert('儲存報價失敗：'+e.message)}}
function convertForm(qid){const q=D.quotes.find(x=>x.id===qid);app.innerHTML=`<div class="page-head"><div><h1>轉 Invoice</h1><p>${esc(q.quotation_no)} · ${hk(q.total)}</p></div><button class="btn light" onclick="setNav('quotation')">返回</button></div><div class="form-card" style="max-width:560px"><div class="field"><label>本期訂金百分比</label><input id="depositPct" type="number" min="0" max="100" value="50"></div><div class="form-actions"><button class="btn green" onclick="convertInvoice('${qid}')">建立 Invoice</button></div></div>`}
async function convertInvoice(qid){try{const q=D.quotes.find(x=>x.id===qid),items=await api('quotation_items','?quotation_id=eq.'+qid+'&select=*&order=sort_order'),dp=n(depositPct.value||50),no=gen('INV');const iv=await api('invoices','',{method:'POST',body:{invoice_no:no,project_id:q.project_id,quotation_id:qid,issue_date:today(),due_date:new Date(Date.now()+7*86400000).toISOString().slice(0,10),subtotal:q.subtotal,discount_amount:q.discount_amount,total:q.total,amount_paid:0,amount_due:q.total,status:'未付款',notes:'DEPOSIT_PERCENT='+dp}});if(items.length)await api('invoice_items','',{method:'POST',body:items.map((x,i)=>({invoice_id:iv[0].id,sort_order:i+1,description:x.description,unit:x.unit,quantity:x.quantity,unit_price:x.unit_price,amount:x.amount}))});await api('quotations','?id=eq.'+qid,{method:'PATCH',body:{status:'已轉Invoice'}});await api('projects','?id=eq.'+q.project_id,{method:'PATCH',body:{contract_amount:q.total,status:'已確認'}});toast('Invoice 已建立');await load();tab='invoice';render()}catch(e){alert('建立 Invoice 失敗：'+e.message)}}
function renderInvoices(){app.innerHTML=`<div class="page-head"><div><h1>Invoice｜應收款</h1><p>查看付款狀態及登記收款。</p></div></div><div class="card"><div style="overflow:auto"><table class="data-table"><thead><tr><th>Invoice</th><th>日期</th><th>狀態</th><th>總額</th><th>已收</th><th>尚欠</th><th></th></tr></thead><tbody>${D.invoices.map(x=>`<tr><td>${esc(x.invoice_no)}</td><td>${esc(x.issue_date||'')}</td><td>${esc(x.status||'')}</td><td>${hk(x.total)}</td><td>${hk(x.amount_paid)}</td><td>${hk(x.amount_due)}</td><td><button class="btn sm light" onclick="viewInvoice('${x.id}')">正式 Invoice</button> ${n(x.amount_due)>0?`<button class="btn sm green" onclick="paymentForm('${x.id}')">收款</button>`:''}</td></tr>`).join('')}</tbody></table></div></div>`}
function paymentForm(id){const x=D.invoices.find(v=>v.id===id);app.innerHTML=`<div class="page-head"><div><h1>登記收款</h1><p>${esc(x.invoice_no)} · 尚欠 ${hk(x.amount_due)}</p></div><button class="btn light" onclick="setNav('invoice')">返回</button></div><div class="form-card" style="max-width:620px"><div class="form-grid"><div class="field"><label>收款金額</label><input id="payAmount" type="number" min="0" max="${n(x.amount_due)}" value="${n(x.amount_due)}"></div><div class="field"><label>收款方式</label><select id="payMethod"><option>FPS 轉數快</option><option>銀行轉帳</option><option>支票</option><option>現金</option><option>其他</option></select></div><div class="field"><label>參考編號</label><input id="payRef"></div><div class="field"><label>備註</label><input id="payRemarks"></div></div><div class="form-actions"><button class="btn green" onclick="savePayment('${id}')">確認收款</button></div></div>`}
async function savePayment(id){const x=D.invoices.find(v=>v.id===id),a=n(payAmount.value);if(a<=0||a>n(x.amount_due)+.01){toast('收款金額不正確');return}try{const rno=gen('RCP');await api('payments','',{method:'POST',body:{project_id:x.project_id,invoice_id:id,receipt_no:rno,payment_date:today(),amount:a,method:payMethod.value,reference_no:payRef.value.trim(),remarks:payRemarks.value.trim()}});const newPaid=n(x.amount_paid)+a,newDue=Math.max(0,n(x.total)-newPaid);await api('invoices','?id=eq.'+id,{method:'PATCH',body:{amount_paid:newPaid,amount_due:newDue,status:newDue<=0?'已付款':'部分付款'}});toast('收款已登記');await load();tab='receipt';render()}catch(e){alert('收款失敗：'+e.message)}}
function renderReceipts(){app.innerHTML=`<div class="page-head"><div><h1>Receipt｜收據</h1><p>所有收款紀錄。</p></div></div><div class="card"><div style="overflow:auto"><table class="data-table"><thead><tr><th>Receipt</th><th>日期</th><th>金額</th><th>方式</th><th>參考編號</th><th></th></tr></thead><tbody>${D.payments.map(x=>`<tr><td>${esc(x.receipt_no||'')}</td><td>${esc(x.payment_date||'')}</td><td>${hk(x.amount)}</td><td>${esc(x.method||'')}</td><td>${esc(x.reference_no||'')}</td><td><button class="btn sm light" onclick="viewReceipt('${x.id}')">正式收據</button></td></tr>`).join('')}</tbody></table></div></div>`}
function renderPricing(){const customer=D.pricing.filter(x=>x.price_tier==='customer'),trade=D.pricing.filter(x=>x.price_tier==='trade');const rows=list=>list.map(x=>`<tr><td>${esc(x.item_code)}</td><td>${esc(x.description)}</td><td>${esc(x.unit)}</td><td>${hk(x.unit_price)}</td><td>${esc(x.pricing_rule||'')}</td></tr>`).join('');app.innerHTML=`<div class="page-head"><div><h1>價目表</h1><p>客戶價同同行價分開顯示。</p></div></div><div class="card"><h3>客戶價</h3><div style="overflow:auto"><table class="data-table"><thead><tr><th>編號</th><th>工程項目</th><th>單位</th><th>單價</th><th>計價規則</th></tr></thead><tbody>${rows(customer)}</tbody></table></div></div><div class="card" style="margin-top:16px"><h3>同行合作價</h3><div style="overflow:auto"><table class="data-table"><thead><tr><th>編號</th><th>工程項目</th><th>單位</th><th>單價</th><th>計價規則</th></tr></thead><tbody>${rows(trade)}</tbody></table></div></div>`}
function formalHeader(en,zh){return `<div class="formal-head"><div class="formal-brand"><b>恆輝建築（香港）有限公司</b><span>UNIBRIGHT CONSTRUCTION (H.K.) LIMITED</span></div><div class="formal-title">${en}<br><small>${zh}</small></div></div>`}
function formalItems(items){return `<table class="formal-table"><thead><tr><th>施工項目</th><th>單位</th><th>數量</th><th>單價</th><th>金額</th></tr></thead><tbody>${items.map((x,i)=>`<tr><td>${i+1}. ${esc(x.description)}</td><td>${esc(x.unit||'項')}</td><td>${n(x.quantity)}</td><td>${hk(x.unit_price)}</td><td>${hk(x.amount??n(x.quantity)*n(x.unit_price))}</td></tr>`).join('')}</tbody></table>`}
function formalSign(){return `<div class="formal-sign"><div>FOR AND BEHALF OF<br><br>UNIBRIGHT CONSTRUCTION (HK) LIMITED<div class="line">Authorized Signature</div></div><div>客戶簽署及確定：<div class="line">Signature <span style="float:right">Date</span></div></div></div>`}
function formalActions(back,extra=''){return `<div class="formal-actions no-print"><button class="btn light" onclick="${back}">返回</button><button class="btn gold" onclick="window.print()">列印／PDF</button>${extra}</div>`}
async function viewQuote(id){try{const q=D.quotes.find(x=>x.id===id)||(await api('quotations','?id=eq.'+id+'&select=*'))[0],items=await api('quotation_items','?quotation_id=eq.'+id+'&select=*&order=sort_order'),p=project(q.project_id),c=clientByProject(q.project_id);app.innerHTML=`<div class="formal-paper">${formalHeader('報價單','[Quotation]')}<table class="formal-meta"><tr><td>報價單編號</td><td>${esc(q.quotation_no)}</td><td>施工地點</td><td>${esc(p?.site_address||'')}</td></tr><tr><td>客戶</td><td>${esc(c.company_name||'')}</td><td>聯絡方式</td><td>${esc(c.contact_name||'')} ${esc(c.phone||'')}<br>${esc(c.email||'')}</td></tr><tr><td>報價日期</td><td>${esc(q.issue_date||'')}</td><td>有效期至</td><td>${esc(q.valid_until||'')}</td></tr></table>${formalItems(items)}<table class="formal-total"><tr><td>折扣 Discount</td><td>${hk(q.discount_amount)}</td></tr><tr class="gold"><td>合計 Total</td><td>${hk(q.total)}</td></tr></table><p>備註：收取訂金50%（${hk(n(q.total)*.5)}），完工7天內收取尾數。</p><table class="formal-pay"><tr><th>收款方式</th><th>收款帳號</th></tr><tr><td>銀行轉帳／支票</td><td>中國工商銀行（亞洲）有限公司 720502009151</td></tr><tr><td>轉數快 FPS</td><td>120437801</td></tr></table>${formalSign()}</div>${formalActions("setNav('quotation')",q.status!=='已轉Invoice'?`<button class="btn green" onclick="convertForm('${id}')">轉 Invoice</button>`:'')}`}catch(e){alert(e.message)}}
async function viewInvoice(id){try{const x=D.invoices.find(v=>v.id===id)||(await api('invoices','?id=eq.'+id+'&select=*'))[0],items=await api('invoice_items','?invoice_id=eq.'+id+'&select=*&order=sort_order'),p=project(x.project_id),c=clientByProject(x.project_id),q=x.quotation_id?D.quotes.find(v=>v.id===x.quotation_id):null,m=String(x.notes||'').match(/DEPOSIT_PERCENT=([0-9.]+)/),dp=m?n(m[1]):50;app.innerHTML=`<div class="formal-paper">${formalHeader('INVOICE','付款通知單')}<table class="formal-meta"><tr><td>Invoice No.</td><td>${esc(x.invoice_no)}</td><td>Invoice Date</td><td>${esc(x.issue_date||'')}</td></tr><tr><td>Ref. Quotation</td><td>${esc(q?.quotation_no||'')}</td><td>Project Ref.</td><td>${esc(p?.project_no||'')}</td></tr><tr><td>BILL TO</td><td>${esc(c.company_name||'')}<br>${esc(c.address||'')}</td><td>PROJECT</td><td>${esc(p?.project_name||'')}<br>${esc(p?.site_address||'')}</td></tr></table>${formalItems(items)}<table class="formal-total"><tr><td>小計 Subtotal</td><td>${hk(x.subtotal)}</td></tr><tr><td>折扣 Discount</td><td>${hk(x.discount_amount)}</td></tr><tr><td>合約總額 Total</td><td>${hk(x.total)}</td></tr><tr class="gold"><td>本期應付 ${dp}% Deposit</td><td>${hk(n(x.total)*dp/100)}</td></tr></table><table class="formal-pay"><tr><th colspan="2">付款資料 PAYMENT DETAILS</th></tr><tr><td>銀行轉帳／支票</td><td>中國工商銀行（亞洲）有限公司 720502009151</td></tr><tr><td>轉數快 FPS</td><td>120437801</td></tr></table>${formalSign()}</div>${formalActions("setNav('invoice')",n(x.amount_due)>0?`<button class="btn green" onclick="paymentForm('${id}')">登記收款</button>`:'')}`}catch(e){alert(e.message)}}
async function viewReceipt(id){try{const x=D.payments.find(v=>v.id===id)||(await api('payments','?id=eq.'+id+'&select=*'))[0],iv=D.invoices.find(v=>v.id===x.invoice_id),p=project(x.project_id),c=clientByProject(x.project_id),all=x.invoice_id?await api('payments','?invoice_id=eq.'+x.invoice_id+'&select=amount'):[x],paid=all.reduce((a,v)=>a+n(v.amount),0),bal=Math.max(0,n(iv?.total)-paid);app.innerHTML=`<div class="formal-paper">${formalHeader('RECEIPT','收據')}<table class="formal-meta"><tr><td>Receipt No.</td><td>${esc(x.receipt_no||'')}</td><td>Receipt Date</td><td>${esc(x.payment_date||'')}</td></tr><tr><td>Ref. Invoice</td><td>${esc(iv?.invoice_no||'')}</td><td>Project Ref.</td><td>${esc(p?.project_no||'')}</td></tr><tr><td>BILL TO</td><td>${esc(c.company_name||'')}<br>${esc(c.contact_name||'')}</td><td>PROJECT</td><td>${esc(p?.project_name||'')}</td></tr></table><table class="formal-table"><thead><tr><th>收款項目</th><th>付款方式</th><th>參考編號</th><th>金額</th></tr></thead><tbody><tr><td>收取 Invoice ${esc(iv?.invoice_no||'')} 款項</td><td>${esc(x.method||'')}</td><td>${esc(x.reference_no||'—')}</td><td>${hk(x.amount)}</td></tr></tbody></table><table class="formal-total"><tr class="gold"><td>本次收款</td><td>${hk(x.amount)}</td></tr><tr><td>累計已收</td><td>${hk(paid)}</td></tr><tr><td>尚欠</td><td>${hk(bal)}</td></tr></table><table class="formal-pay"><tr><th colspan="2">收款資料 PAYMENT DETAILS</th></tr><tr><td>收款方式</td><td>${esc(x.method||'')}</td></tr><tr><td>參考編號</td><td>${esc(x.reference_no||'—')}</td></tr><tr><td>備註</td><td>${esc(x.remarks||'—')}</td></tr></table>${formalSign()}</div>${formalActions("setNav('receipt')")}`}catch(e){alert(e.message)}}
load();
