(()=>{'use strict';
function visible(el){if(!el)return false;const r=el.getBoundingClientRect();const s=getComputedStyle(el);return s.display!=='none'&&s.visibility!=='hidden'&&r.width>250&&r.height>350;}
function score(el){if(!el)return-1;let n=0;const c=String(el.className||'');const t=(el.innerText||'').toUpperCase();if(c.includes('a4-sheet'))n+=100;if(c.includes('ub-a4'))n+=95;if(el.tagName==='ARTICLE')n+=40;if(/INVOICE|QUOTATION|RECEIPT|報價單|付款通知單|收據/.test(t))n+=60;if(el.querySelectorAll('table').length>=2)n+=30;if(visible(el))n+=50;const r=el.getBoundingClientRect();if(r.width>500&&r.height>700)n+=25;return n;}
function findDoc(){const roots=[document.querySelector('.single-preview'),document.querySelector('.preview-stage'),document.getElementById('app'),document.body].filter(Boolean);const sels=['.a4-sheet','.ub-a4','.a4-scale-box>article','.a4-scale-box>*','.preview-stage article','.single-preview article','article'];let list=[];for(const root of roots){for(const sel of sels){try{root.querySelectorAll(sel).forEach(x=>list.push(x))}catch(_){}}}list=[...new Set(list)].filter(x=>score(x)>50).sort((a,b)=>score(b)-score(a));return list[0]||null;}
function normalizeClone(src){const c=src.cloneNode(true);if(!c.classList.contains('a4-sheet'))c.classList.add('a4-sheet');c.style.transform='none';c.style.transformOrigin='top left';c.style.margin='0';c.style.boxShadow='none';c.style.width='794px';c.style.height='1123px';c.style.minHeight='1123px';c.style.maxHeight='1123px';c.style.overflow='hidden';c.style.background='#fff';return c;}
async function buildBlob(){const src=findDoc();if(!src)throw new Error('畫面上搵唔到正式 A4 文件');if(!window.html2pdf)throw new Error('PDF 引擎未載入');const clone=normalizeClone(src);const host=document.createElement('div');host.style.cssText='position:fixed;left:-12000px;top:0;width:794px;height:1123px;overflow:hidden;background:#fff;z-index:-1;pointer-events:none';host.appendChild(clone);document.body.appendChild(host);try{await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const worker=window.html2pdf().set({margin:0,image:{type:'jpeg',quality:.99},html2canvas:{scale:2,useCORS:true,allowTaint:true,backgroundColor:'#fff',logging:false,scrollX:0,scrollY:0,windowWidth:794,windowHeight:1123},jsPDF:{unit:'mm',format:'a4',orientation:'portrait',compress:true},pagebreak:{mode:['avoid-all','css','legacy']}}).from(clone).toPdf();const pdf=await worker.get('pdf');while(pdf.getNumberOfPages()>1)pdf.deletePage(pdf.getNumberOfPages());const blob=pdf.output('blob');if(!blob||blob.size<1000)throw new Error('PDF 建立失敗');return blob}finally{host.remove();}}
function docName(){const src=findDoc();const txt=src?.innerText||document.body.innerText||'';const title=/RECEIPT|收據/i.test(txt)?'Receipt':/INVOICE|付款通知單/i.test(txt)?'Invoice':'Quotation';const no=txt.match(/(?:QO|TQ|INV|RCP|RC)[A-Z0-9\/-]*/i)?.[0]||new Date().toISOString().slice(0,10);return `UNIBRIGHT_${title}_${String(no).replace(/[\\/:*?"<>|]+/g,'-')}.pdf`;}
window.downloadCurrentPDF=window.exportCurrentPDF=async function(name){try{const blob=await buildBlob();const filename=name||docName();const file=new File([blob],filename,{type:'application/pdf'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){try{await navigator.share({files:[file],title:filename});return true}catch(e){if(e?.name==='AbortError')return false}}const url=URL.createObjectURL(blob);if(/iPhone|iPad|iPod|Android/i.test(navigator.userAgent)){const w=window.open(url,'_blank');if(!w)location.href=url}else{const a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove()}setTimeout(()=>URL.revokeObjectURL(url),300000);return true}catch(e){console.error('V16 PDF',e);alert('PDF 下載失敗：'+String(e?.message||e));return false;}};
window.printCurrentA4=window.printA4=function(){const src=findDoc();if(!src){alert('畫面上搵唔到正式 A4 文件');return}const html=normalizeClone(src).outerHTML;const w=window.open('','_blank');if(!w){alert('瀏覽器阻止咗列印視窗');return}w.document.open();w.document.write(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zoechow412-ui/m@f5f55fb1b62550121a2053b213d4248ed31a028f/unibright-ops/v15/a4-approved.css"><style>html,body{margin:0!important;padding:0!important;width:210mm!important;height:297mm!important;overflow:hidden!important;background:#fff!important}.a4-sheet{width:210mm!important;height:297mm!important;min-height:297mm!important;max-height:297mm!important;margin:0!important;box-shadow:none!important;transform:none!important;overflow:hidden!important}@page{size:A4 portrait;margin:0}</style></head><body>${html}<script>window.onload=()=>setTimeout(()=>{window.focus();window.print()},350)<\/script></body></html>`);w.document.close();};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const t=(b.textContent||'').replace(/\s+/g,' ').trim();if(t==='下載 PDF'||t==='下載／儲存 PDF'||t==='下載 / 儲存 PDF'){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();window.downloadCurrentPDF();return}if(t==='列印'){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();window.printCurrentA4();}},true);
window.UNIBRIGHT_V16=()=>({doc:!!findDoc(),score:score(findDoc()),pdf:typeof window.downloadCurrentPDF==='function',print:typeof window.printCurrentA4==='function'});
})();