(()=>{
'use strict';
window.UNIBRIGHT_RESPONSIBLE_BUILD='20260914-v25-responsible-person-1';
const s=document.createElement('style');s.id='ub-v25-responsible-css';s.textContent=`
.ub-responsible-badge{display:inline-flex;align-items:center;gap:6px;margin:7px 0 2px;padding:5px 9px;border-radius:999px;background:#f5f8fb;border:1px solid #e0e7ed;color:#0b2c5b;font-size:12px;font-weight:800}.ub-responsible-badge span{color:#607386;font-weight:600}.ub-responsible-field{grid-column:span 2}.ub-responsible-field input{font-weight:700}@media(max-width:700px){.ub-responsible-field{grid-column:1/-1}}
`;document.head.appendChild(s);
function projectList(){return D.projects||[]}
window.renderProjects=function(){const list=filteredProjects();app.innerHTML=`<div class="page-head"><div><h1>工程項目</h1><p>工程資料、客戶資料、進度、負責人同收款放埋一齊。</p></div></div><div class="stack">${list.map((p,i)=>{const s=sumProject(p.id),c=clientByProject(p.id);return `<div class="project-card"><div class="thumb thumb-${i%3+1}"></div><div><h3>${esc(p.project_name)}</h3><p>${esc(p.project_no)} · ${esc(p.site_address||'')}</p><p>${esc(c.company_name||'')} ${esc(c.contact_name||'')}</p><div class="ub-responsible-badge">👤 <span>負責人</span> ${esc(p.responsible_person||'未指定')}</div><div class="finance"><span>進度<b>${n(p.progress_percent)}%</b></span><span>合約額<b>${hk(p.contract_amount)}</b></span><span>已收<b>${hk(s.received_amount)}</b></span><span>尚欠<b>${hk(s.outstanding_amount??p.contract_amount)}</b></span></div></div><div class="ub-project-actions"><button class="btn light" onclick="editProject('${p.id}')">編輯項目</button><button class="btn light ub-delete-btn" onclick="deleteProject('${p.id}')">刪除項目</button></div></div>`}).join('')||'<div class="empty-state">未有工程項目。</div>'}</div>`};
window.showProjectForm=function(p){const c=p?clientByProject(p.id):{};if(!p){toast('新工程請由新報價流程建立');return}app.innerHTML=`<div class="page-head"><div><h1>編輯項目</h1><p>工程資料一次過修改，儲存後直接寫入資料庫。</p></div><button class="btn light" onclick="setNav('projects')">返回</button></div><div class="form-card colorful-form"><div class="form-section blue-section"><div class="section-icon">🏗</div><div><b>工程資料</b><small>名稱、地址、狀態、負責人及合約</small></div></div><div class="form-grid"><div class="field"><label>工程／項目名稱</label><input id="epname" value="${esc(p.project_name||'')}"></div><div class="field"><label>工程編號</label><input id="epno" value="${esc(p.project_no||'')}"></div><div class="field full"><label>施工地址</label><textarea id="esite">${esc(p.site_address||'')}</textarea></div><div class="field"><label>負責人</label><input id="eresponsible" class="ub-responsible-input" value="${esc(p.responsible_person||'')}" placeholder="例如：陳先生／Zoe"></div><div class="field"><label>狀態</label><select id="estatus">${['報價中','已確認','施工中','待收款','已完成'].map(x=>`<option ${p.status===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>工程進度 %</label><input id="eprogress" type="number" min="0" max="100" value="${n(p.progress_percent)}"></div><div class="field"><label>合約金額</label><input id="econtract" type="number" min="0" value="${n(p.contract_amount)}"></div></div><div class="form-section yellow-section"><div class="section-icon">👤</div><div><b>客戶資料</b><small>報價、Invoice、Receipt 會直接沿用</small></div></div><div class="form-grid"><div class="field"><label>客戶／公司名稱</label><input id="ecname" value="${esc(c.company_name||'')}"></div><div class="field"><label>聯絡人</label><input id="econtact" value="${esc(c.contact_name||'')}"></div><div class="field"><label>電話</label><input id="ephone" value="${esc(c.phone||'')}"></div><div class="field"><label>Email</label><input id="eemail" value="${esc(c.email||'')}"></div><div class="field full"><label>客戶地址</label><textarea id="ecaddr">${esc(c.address||'')}</textarea></div></div><div class="form-actions"><button class="btn light" onclick="setNav('projects')">取消</button><button class="btn green" onclick="saveProject('${p.id}','${c.id||''}')">儲存項目</button></div></div>`};
window.saveProject=async function(pid,cid){if(!pid){toast('新工程請由新報價流程建立');return}if(!val('epname').trim()){toast('請輸入工程名稱');return}try{let clientId=cid;if(clientId){await api('clients','?id=eq.'+clientId,{method:'PATCH',body:{company_name:val('ecname').trim(),contact_name:val('econtact').trim(),phone:val('ephone').trim(),email:val('eemail').trim(),address:val('ecaddr').trim()}})}else{const cc=await api('clients','',{method:'POST',body:{company_name:val('ecname').trim()||'未命名客戶',contact_name:val('econtact').trim(),phone:val('ephone').trim(),email:val('eemail').trim(),address:val('ecaddr').trim()}});clientId=cc[0].id}const body={project_no:val('epno').trim(),client_id:clientId,project_name:val('epname').trim(),site_address:val('esite').trim(),responsible_person:val('eresponsible').trim(),status:val('estatus'),progress_percent:Math.max(0,Math.min(100,n(val('eprogress')))),contract_amount:n(val('econtract'))};await api('projects','?id=eq.'+pid,{method:'PATCH',body});await api('project_progress','',{method:'POST',body:{project_id:pid,progress_percent:body.progress_percent,status:body.status,update_note:'更新工程資料'}});toast('工程資料已儲存');await refreshData();tab='projects';renderProjects()}catch(e){alert('儲存失敗：'+String(e?.message||e))}};
const oldDash=window.renderDashboard;if(typeof oldDash==='function')window.renderDashboard=function(){oldDash();document.querySelectorAll('.project-row').forEach(row=>{const b=row.querySelector('button[onclick*="editProject"]');const m=b?.getAttribute('onclick')?.match(/editProject\('([^']+)'\)/);if(!m)return;const p=project(m[1]);if(!p||row.querySelector('.ub-responsible-badge'))return;const sub=row.querySelector('.project-sub');if(sub)sub.insertAdjacentHTML('afterend',`<div class="ub-responsible-badge">👤 <span>負責人</span> ${esc(p.responsible_person||'未指定')}</div>`)})};
window.UNIBRIGHT_RESPONSIBLE_HEALTH=()=>({build:window.UNIBRIGHT_RESPONSIBLE_BUILD,column:true,projectCount:projectList().length,field:document.getElementById('eresponsible')!==null});
})();