(()=>{
'use strict';
window.UNIBRIGHT_PROJECT_HUB_BUILD='20260912-v22-project-hub';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const statusOptions=['報價中','已確認','施工中','待收款','已完成'];
function css(){if(document.getElementById('ub-project-hub-css'))return;const s=document.createElement('style');s.id='ub-project-hub-css';s.textContent=`
.project-row.ub-project-click{cursor:pointer;border-radius:14px;padding-left:8px;padding-right:8px;transition:.15s}.project-row.ub-project-click:hover{background:#f5f9fb}.hub-head{display:flex;justify-content:space-between;gap:16px;align-items:flex-start;margin-bottom:18px}.hub-head h1{margin:3px 0 5px;font-size:32px;color:#082b59}.hub-head p{margin:0;color:#71839c}.hub-actions{display:flex;gap:8px;flex-wrap:wrap;justify-content:flex-end}.hub-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:16px}.hub-kpi{background:#fff;border:1px solid #e5ebee;border-radius:16px;padding:15px;box-shadow:0 8px 24px rgba(11,44,91,.06)}.hub-kpi small{display:block;color:#71839c;font-weight:700}.hub-kpi b{display:block;font-size:23px;margin-top:6px;color:#082b59}.hub-grid{display:grid;grid-template-columns:minmax(300px,.85fr) minmax(0,1.65fr);gap:16px;align-items:start}.hub-panel{background:#fff;border:1px solid #e5ebee;border-radius:18px;padding:16px;box-shadow:0 8px 24px rgba(11,44,91,.06)}.hub-panel h2{margin:0 0 12px;font-size:19px;color:#082b59}.hub-follow-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.hub-field{display:grid;gap:5px}.hub-field.full{grid-column:1/-1}.hub-field label{font-size:11px;font-weight:800;color:#71839c}.hub-field input,.hub-field select,.hub-field textarea{width:100%;border:1px solid #d9e2e7;border-radius:11px;padding:10px 11px;background:#fff;color:#0b2c5b}.hub-field textarea{min-height:76px;resize:vertical}.hub-save{display:flex;justify-content:flex-end;margin-top:10px}.hub-history{display:grid;gap:8px;margin-top:14px}.hub-history-item{padding:9px 10px;background:#f7fafb;border-radius:10px;font-size:11px;color:#526a82}.hub-history-item b{color:#082b59}.hub-doc-section{margin-bottom:16px}.hub-doc-section:last-child{margin-bottom:0}.hub-doc-title{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}.hub-doc-title h3{margin:0;font-size:16px;color:#082b59}.hub-doc-list{display:grid;gap:8px}.hub-doc{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:10px;align-items:center;padding:11px 12px;border:1px solid #e6ecef;border-radius:12px;background:#fbfcfc}.hub-doc-main{min-width:0}.hub-doc-main b{display:block;color:#082b59;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.hub-doc-main span{display:block;margin-top:3px;color:#71839c;font-size:11px}.hub-doc-main strong{display:block;margin-top:5px;color:#0a2e1f}.hub-doc-actions{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.hub-empty{padding:13px;border:1px dashed #d3dde2;border-radius:11px;color:#8192a4;text-align:center;font-size:12px}.hub-due{background:#fff9ed;border-color:#ead39b}.hub-due .hub-doc-main strong{color:#9b6511}.hub-client{margin-top:12px;padding:11px;border-radius:12px;background:#f5f9fb;color:#526a82;font-size:12px;line-height:1.55}.hub-client b{color:#082b59}.hub-return-note{font-size:10px;color:#7c8da0;margin-top:7px}
@media(max-width:900px){.hub-kpis{grid-template-columns:1fr 1fr}.hub-grid{grid-template-columns:1fr}.hub-head{display:block}.hub-actions{justify-content:stretch;margin-top:12px}.hub-actions .btn{flex:1}.hub-doc{grid-template-columns:1fr}.hub-doc-actions{justify-content:stretch}.hub-doc-actions .btn{flex:1;min-width:78px}.hub-follow-grid{grid-template-columns:1fr}.hub-field.full{grid-column:auto}}
`;
document.head.appendChild(s)}
function money(v){return typeof hk==='function'?hk(v):'HK$'+Number(v||0).toLocaleString('en-HK',{minimumFractionDigits:2,maximumFractionDigits:2})}
function e(v){return typeof esc==='function'?esc(v):String(v??'')}
function bindDashboardRows(){try{const rows=[...document.querySelectorAll('.project-list .project-row')];if(!rows.length)return;const list=(typeof filteredProjects==='function'?filteredProjects():D.projects).slice(0,rows.length);rows.forEach((row,i)=>{const p=list[i];if(!p)return;row.classList.add('ub-project-click');row.dataset.projectId=p.id;row.onclick=ev=>{ev.preventDefault();ev.stopPropagation();window.openProjectHub(p.id)};const b=row.querySelector('button');if(b)b.onclick=ev=>{ev.preventDefault();ev.stopPropagation();window.openProjectHub(p.id)}})}catch(err){console.warn('bindDashboardRows',err)}}
function docButtons(kind,id,pid,extra=''){return `<div class="hub-doc-actions"><button class="btn light sm" onclick="openProjectDocument('${kind}','${id}')">預覽</button><button class="btn gold sm" onclick="downloadProjectDocument('${kind}','${id}','${pid}')">下載 PDF</button>${extra}</div>`}
function fmtDate(v){if(!v)return'—';return String(v).slice(0,10)}
window.openProjectHub=async function(id){css();const p=project(id)||D.projects.find(x=>x.id===id);if(!p){alert('搵唔到工程');return}const c=clientByProject(id)||{};const s=typeof sumProject==='function'?sumProject(id):{};const qs=D.quotes.filter(x=>x.project_id===id);const ivs=D.invoices.filter(x=>x.project_id===id);const pays=D.payments.filter(x=>x.project_id===id);const received=pays.reduce((a,x)=>a+n(x.amount),0);const outstanding=ivs.reduce((a,x)=>a+n(x.amount_due),0);let hist=[];try{hist=await api('project_progress','?project_id=eq.'+id+'&select=*&order=created_at.desc&limit=6')}catch(_){hist=[]}
const due=ivs.filter(x=>n(x.amount_due)>0);
const quoteRows=qs.length?qs.map(q=>`<div class="hub-doc"><div class="hub-doc-main"><b>${e(q.quotation_no)}</b><span>${fmtDate(q.issue_date)} · ${e(q.status||'')}</span><strong>${money(q.total)}</strong></div>${docButtons('quote',q.id,id,q.status!=='已轉Invoice'?`<button class="btn green sm" onclick="invoiceWorkbench('${q.id}')">轉 Invoice</button>`:'')}</div>`).join(''):'<div class="hub-empty">未有報價單</div>';
const invoiceRows=ivs.length?ivs.map(x=>`<div class="hub-doc ${n(x.amount_due)>0?'hub-due':''}"><div class="hub-doc-main"><b>${e(x.invoice_no)}</b><span>${fmtDate(x.issue_date)} · ${e(x.status||'')}</span><strong>尚欠 ${money(x.amount_due)}</strong></div>${docButtons('invoice',x.id,id,n(x.amount_due)>0?`<button class="btn green sm" onclick="paymentWorkbench('${x.id}')">收款</button>`:'')}</div>`).join(''):'<div class="hub-empty">未有 Invoice</div>';
const receiptRows=pays.length?pays.map(x=>`<div class="hub-doc"><div class="hub-doc-main"><b>${e(x.receipt_no||'Receipt')}</b><span>${fmtDate(x.payment_date)} · ${e(x.method||'')}</span><strong>${money(x.amount)}</strong></div>${docButtons('receipt',x.id,id)}</div>`).join(''):'<div class="hub-empty">未有 Receipt</div>';
const dueRows=due.length?due.map(x=>`<div class="hub-doc hub-due"><div class="hub-doc-main"><b>${e(x.invoice_no)}</b><span>到期：${fmtDate(x.due_date)}</span><strong>待收 ${money(x.amount_due)}</strong></div><div class="hub-doc-actions"><button class="btn green sm" onclick="paymentWorkbench('${x.id}')">登記收款</button><button class="btn light sm" onclick="viewInvoice('${x.id}')">睇 Invoice</button></div></div>`).join(''):'<div class="hub-empty">目前冇待收款 Invoice</div>';
const histRows=hist.length?hist.map(h=>`<div class="hub-history-item"><b>${fmtDate(h.created_at)} · ${e(h.status||'')}</b><br>${e(h.update_note||'工程更新')} · ${n(h.progress_percent)}%</div>`).join(''):'<div class="hub-empty">未有跟進紀錄</div>';
app.innerHTML=`<div class="hub-head"><div><span class="eyebrow">PROJECT FOLLOW-UP</span><h1>${e(p.project_name||'工程')}</h1><p>${e(p.project_no||'')} · ${e(p.site_address||'')}</p></div><div class="hub-actions"><button class="btn light" onclick="setNav('dashboard')">返回首頁</button><button class="btn" onclick="newQuoteForProject('${id}')">＋ 新報價</button></div></div>
<div class="hub-kpis"><div class="hub-kpi"><small>工程進度</small><b>${n(p.progress_percent)}%</b></div><div class="hub-kpi"><small>合約金額</small><b>${money(p.contract_amount)}</b></div><div class="hub-kpi"><small>已收款</small><b>${money(received||s.received_amount)}</b></div><div class="hub-kpi"><small>待收款</small><b>${money(outstanding)}</b></div></div>
<div class="hub-grid"><div><section class="hub-panel"><h2>更新／跟進</h2><div class="hub-follow-grid"><div class="hub-field"><label>工程狀態</label><select id="hubStatus">${statusOptions.map(x=>`<option ${p.status===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="hub-field"><label>進度 %</label><input id="hubProgress" type="number" min="0" max="100" value="${n(p.progress_percent)}"></div><div class="hub-field full"><label>今次跟進內容</label><textarea id="hubNote" placeholder="例如：今日已追客戶訂金；等候入數；已安排師傅…"></textarea></div></div><div class="hub-save"><button class="btn green" onclick="saveProjectFollowUp('${id}')">儲存跟進</button></div><div class="hub-client"><b>${e(c.company_name||'未填客戶')}</b><br>${e(c.contact_name||'')} ${e(c.phone||'')}<br>${e(c.email||'')}</div><div class="hub-history">${histRows}</div></section>
<section class="hub-panel" style="margin-top:16px"><h2>收款跟進</h2><div class="hub-doc-list">${dueRows}</div></section></div>
<section class="hub-panel"><div class="hub-doc-section"><div class="hub-doc-title"><h3>Quotation｜報價單</h3><button class="btn light sm" onclick="newQuoteForProject('${id}')">＋ 新報價</button></div><div class="hub-doc-list">${quoteRows}</div></div><div class="hub-doc-section"><div class="hub-doc-title"><h3>Invoice｜付款通知</h3></div><div class="hub-doc-list">${invoiceRows}</div></div><div class="hub-doc-section"><div class="hub-doc-title"><h3>Receipt｜收據</h3></div><div class="hub-doc-list">${receiptRows}</div></div><div class="hub-return-note">下載 PDF 會使用同一份正式 A4 文件格式。</div></section></div>`;
window.scrollTo({top:0,behavior:'smooth'})}
window.saveProjectFollowUp=async function(id){const p=project(id)||D.projects.find(x=>x.id===id);if(!p)return;const progress=Math.max(0,Math.min(100,n(document.getElementById('hubProgress')?.value)));const status=document.getElementById('hubStatus')?.value||p.status||'施工中';const note=(document.getElementById('hubNote')?.value||'').trim()||'工程跟進更新';try{await api('projects','?id=eq.'+id,{method:'PATCH',body:{progress_percent:progress,status}});await api('project_progress','',{method:'POST',body:{project_id:id,progress_percent:progress,status,update_note:note}});toast('跟進已更新');await refreshData();await window.openProjectHub(id)}catch(err){alert('更新跟進失敗：'+String(err?.message||err))}}
window.newQuoteForProject=function(id){newQuote();setTimeout(()=>{const q=document.getElementById('qproject');if(q){q.value=id;if(typeof projectChoiceChanged==='function')projectChoiceChanged();if(typeof updateQuotePreview==='function')updateQuotePreview()}},0)}
window.openProjectDocument=async function(kind,id){if(kind==='quote')return viewQuote(id);if(kind==='invoice')return viewInvoice(id);if(kind==='receipt')return viewReceipt(id)}
window.downloadProjectDocument=async function(kind,id,pid){const mobile=/iPhone|iPad|iPod|Android/i.test(navigator.userAgent);try{await window.openProjectDocument(kind,id);await sleep(450);if(mobile){toast('已開啟正式文件，撳「下載 PDF」即可儲存');return}if(typeof window.exportCurrentPDF!=='function')throw new Error('PDF 下載功能未載入');const ok=await window.exportCurrentPDF();if(ok!==false)setTimeout(()=>window.openProjectHub(pid),250)}catch(err){alert('下載文件失敗：'+String(err?.message||err))}}
css();
const mo=new MutationObserver(()=>requestAnimationFrame(bindDashboardRows));mo.observe(document.getElementById('app')||document.body,{subtree:true,childList:true});setTimeout(bindDashboardRows,300);setTimeout(bindDashboardRows,1000);
})();