(()=>{
'use strict';
const LOGO='https://raw.githubusercontent.com/zoechow412-ui/m/362161d041eb12d34a334244a138baec6f1bd649/unibright-ops/v8/logo-original.png';
const isiOS=()=>/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
const paper=()=>document.querySelector('.a4-sheet');
const safe=s=>String(s||'UNIBRIGHT').replace(/[\\/:*?"<>|]+/g,'-').replace(/\s+/g,' ').trim();
function fileName(p){const title=p?.querySelector('.a4-title b')?.textContent?.trim()||'Document';const txt=p?.innerText||'';const no=txt.match(/(?:QO|TQ|INV|RCP|RC)[A-Z0-9\/-]*/i)?.[0]||new Date().toISOString().slice(0,10);return safe(`UNIBRIGHT_${title}_${no}`)+'.pdf'}
function ensureLogo(root=document){root.querySelectorAll('.a4-logo').forEach(box=>{box.style.background='none';box.style.width='245px';box.style.height='78px';box.style.minHeight='78px';let img=box.querySelector('img');if(!img){img=document.createElement('img');box.prepend(img)}if(img.getAttribute('src')!==LOGO)img.setAttribute('src',LOGO);img.alt='恆輝建築（香港）有限公司 UNIBRIGHT CONSTRUCTION (H.K.) LIMITED';Object.assign(img.style,{display:'block',opacity:'1',visibility:'visible',width:'245px',height:'78px',maxWidth:'245px',maxHeight:'78px',objectFit:'contain',objectPosition:'left center'})})}
function findProjectNo(p){let m=(p?.innerText||'').match(/\bQU\d{8}-\d+\b|\bUB-\d{8}-\d+\b/);if(m)return m[0];try{if(typeof D!=='undefined'&&Array.isArray(D.projects)){const txt=p?.innerText||'';const hit=D.projects.find(x=>(x.project_name&&txt.includes(x.project_name))||(x.site_address&&txt.includes(x.site_address)));if(hit?.project_no)return hit.project_no}}catch(_){}m=(document.body.innerText||'').match(/\bQU\d{8}-\d+\b|\bUB-\d{8}-\d+\b/);return m?.[0]||''}
function ensureProjectRef(root=document){root.querySelectorAll('.a4-sheet').forEach(p=>{const no=findProjectNo(p);if(!no)return;[...p.querySelectorAll('.a4-meta td.label')].forEach(td=>{const t=(td.textContent||'').trim();if(/Project\s*Ref\.?/i.test(t)||/工程編號/.test(t)){const val=td.nextElementSibling;if(val&&(!val.textContent.trim()||val.textContent.trim()==='—'))val.textContent=no}})})}
function patch(root=document){ensureLogo(root);ensureProjectRef(root)}
async function waitImages(root){const imgs=[...root.querySelectorAll('img')];await Promise.all(imgs.map(img=>img.complete?Promise.resolve():new Promise(r=>{img.onload=img.onerror=r;setTimeout(r,2500)})))}
async function makePdfBlob(){const p=paper();if(!p)throw new Error('未有可下載嘅 A4 文件');patch(p);await waitImages(p);if(!window.html2pdf)throw new Error('PDF 引擎未載入');const clone=p.cloneNode(true);patch(clone);Object.assign(clone.style,{transform:'none',transformOrigin:'top left',margin:'0',boxShadow:'none',width:'794px',height:'1120px',minHeight:'1120px',maxHeight:'1120px',overflow:'hidden',background:'#fff'});const host=document.createElement('div');Object.assign(host.style,{position:'fixed',left:'-12000px',top:'0',width:'794px',height:'1120px',overflow:'hidden',background:'#fff',pointerEvents:'none',zIndex:'-1'});host.appendChild(clone);document.body.appendChild(host);try{await waitImages(clone);const worker=window.html2pdf().set({margin:0,image:{type:'jpeg',quality:.99},html2canvas:{scale:2,useCORS:true,allowTaint:false,backgroundColor:'#fff',logging:false,scrollX:0,scrollY:0,windowWidth:794,windowHeight:1120},jsPDF:{unit:'mm',format:'a4',orientation:'portrait',compress:true},pagebreak:{mode:['avoid-all','css','legacy']}}).from(clone).toPdf();const pdf=await worker.get('pdf');if(pdf.getNumberOfPages()>1){while(pdf.getNumberOfPages()>1)pdf.deletePage(pdf.getNumberOfPages())}const blob=pdf.output('blob');if(!blob||blob.size<1000)throw new Error('PDF 建立失敗');return blob}finally{host.remove()}}
async function downloadPdf(){const p=paper();if(!p){alert('未有可下載嘅 A4 文件');return}const name=fileName(p);try{const blob=await makePdfBlob();const file=new File([blob],name,{type:'application/pdf'});if(isiOS()&&navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){try{await navigator.share({files:[file],title:name});return}catch(e){if(e?.name==='AbortError')return}}
const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.target='_blank';a.rel='noopener';document.body.appendChild(a);a.click();a.remove();if(isiOS())setTimeout(()=>{try{window.open(url,'_blank')}catch(_){}},50);setTimeout(()=>URL.revokeObjectURL(url),300000)}catch(e){console.error(e);alert('PDF 下載失敗：'+String(e?.message||e))}}
function printOnePage(){const p=paper();if(!p){alert('未有可列印嘅 A4 文件');return}patch(p);const w=window.open('','_blank');if(!w){alert('瀏覽器阻止咗列印視窗，請允許彈出視窗後再試。');return}const html=p.outerHTML;w.document.open();w.document.write(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>UNIBRIGHT Document</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zoechow412-ui/m@efa6db81b0c1da38c1abef143c9080365fd60f6c/unibright-ops/v7/a4.css"><style>@page{size:A4 portrait;margin:0}html,body{margin:0!important;padding:0!important;width:210mm!important;height:296mm!important;overflow:hidden!important;background:#fff!important}.a4-sheet{width:210mm!important;height:296mm!important;min-height:296mm!important;max-height:296mm!important;margin:0!important;padding:11mm 12mm 9mm!important;box-shadow:none!important;transform:none!important;overflow:hidden!important;page-break-after:avoid!important;break-after:avoid!important}.a4-logo{background:none!important;width:245px!important;height:78px!important;min-height:78px!important}.a4-logo img{display:block!important;opacity:1!important;visibility:visible!important;width:245px!important;height:78px!important;object-fit:contain!important;object-position:left center!important}</style></head><body>${html}<script>window.onload=()=>setTimeout(()=>{window.focus();window.print()},500)<\/script></body></html>`);w.document.close()}
window.exportCurrentPDF=downloadPdf;window.downloadPDF=downloadPdf;window.printA4=printOnePage;
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const t=(b.textContent||'').replace(/\s+/g,' ').trim();if(/下載/.test(t)&&/PDF/.test(t)){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();downloadPdf();return}if(/^列印$/.test(t)||/^列印\s*\/\s*PDF$/.test(t)||/^列印／PDF$/.test(t)){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();printOnePage();return}},true);
let queued=false;const obs=new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;patch(document)})});obs.observe(document.getElementById('app')||document.body,{subtree:true,childList:true});
window.addEventListener('load',()=>patch(document),{once:true});setTimeout(()=>patch(document),100);setTimeout(()=>patch(document),800);
window.UNIBRIGHT_V13=()=>({logo:LOGO,pdf:typeof window.exportCurrentPDF==='function',print:typeof window.printA4==='function',paper:!!paper(),projectRef:findProjectNo(paper())});
})();