(()=>{'use strict';
window.UNIBRIGHT_BUILD='20260912-v21-final-tested-engine';
const A4W=794,A4H=1123;
const LOGO_B64_URL='https://cdn.jsdelivr.net/gh/zoechow412-ui/m@8e50e39fee5071571ca3efe28b1ab5677c9ca2ce/unibright-ops/v21/logo.b64.txt';
let logoData='';
function injectCss(){if(document.getElementById('ub-v21-css'))return;const s=document.createElement('style');s.id='ub-v21-css';s.textContent=`.a4-actions{display:flex!important;flex-wrap:wrap!important;gap:8px!important;justify-content:flex-end!important;align-items:center!important;position:static!important;max-width:100%!important}.a4-actions .btn{white-space:normal!important}.a4-logo{display:flex!important;align-items:center!important;gap:12px!important}.a4-logo img.ub-v21-logo{display:block!important;width:58px!important;height:76px!important;object-fit:contain!important;flex:0 0 58px!important}.ub-v21-brand b{display:block!important;color:#12315b!important;font-size:17px!important;white-space:nowrap!important}.ub-v21-brand span{display:block!important;color:#12315b!important;font-size:10.5px!important;margin-top:4px!important;white-space:nowrap!important}@media(max-width:700px){.content{overflow-x:hidden!important}.single-preview{width:100%!important;min-width:0!important}.a4-actions{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;width:100%!important;justify-content:stretch!important;margin:12px 0 8px!important;padding:0!important;left:auto!important;right:auto!important;top:auto!important;bottom:auto!important}.a4-actions .btn{width:100%!important;min-width:0!important;margin:0!important;padding:10px 8px!important;font-size:13px!important}.preview-stage{overflow:hidden!important}.page-head{align-items:flex-start!important;flex-wrap:wrap!important}.page-head h1{font-size:29px!important}.search{width:min(100%,430px)!important}.topbar{padding:0 14px!important}}`;document.head.appendChild(s)}
async function loadLogo(){if(logoData)return logoData;const r=await fetch(LOGO_B64_URL,{cache:'force-cache'});if(!r.ok)throw new Error('Logo 資料載入失敗');const b=(await r.text()).trim();if(b.length<1000)throw new Error('Logo 資料不完整');logoData='data:image/jpeg;base64,'+b;const im=new Image();im.src=logoData;await new Promise((res,rej)=>{im.onload=res;im.onerror=()=>rej(new Error('Logo 圖片解碼失敗'))});if(!im.naturalWidth)throw new Error('Logo 圖片無效');return logoData}
async function patchPaper(p){if(!p)return null;const data=await loadLogo();const box=p.querySelector('.a4-logo');if(!box)throw new Error('文件抬頭缺少 Logo 區');box.innerHTML=`<img class="ub-v21-logo" src="${data}" alt="UNIBRIGHT blue B logo"><div class="ub-v21-brand"><b>恒輝建築（香港）有限公司</b><span>UNIBRIGHT CONSTRUCTION (H.K.) LTD.</span></div>`;return p}
function getPaper(){return document.querySelector('.single-preview .a4-sheet,.preview-stage .a4-sheet,.a4-sheet')}
async function patchAll(){injectCss();for(const p of document.querySelectorAll('.a4-sheet')){try{await patchPaper(p)}catch(e){console.error('V21 logo patch',e)}}document.querySelectorAll('button').forEach(b=>{const t=(b.textContent||'').replace(/\s+/g,' ').trim();const oc=b.getAttribute('onclick')||'';if(/列印\s*[\/／]\s*PDF/.test(t)||/exportCurrentPDF\(|printA4\(/.test(oc)){if(/列印/.test(t)&&!/下載/.test(t))b.textContent='下載 PDF'}})}
async function cloneA4(){const src=getPaper();if(!src)throw new Error('畫面上搵唔到正式 A4 文件');const c=src.cloneNode(true);await patchPaper(c);Object.assign(c.style,{transform:'none',transformOrigin:'top left',width:A4W+'px',height:A4H+'px',minHeight:A4H+'px',maxHeight:A4H+'px',margin:'0',boxShadow:'none',overflow:'hidden',background:'#fff',position:'relative'});c.style.setProperty('transform','none','important');c.style.setProperty('width',A4W+'px','important');c.style.setProperty('height',A4H+'px','important');c.style.setProperty('min-height',A4H+'px','important');c.style.setProperty('max-height',A4H+'px','important');return c}
async function renderA4Canvas(){if(!window.html2canvas)throw new Error('PDF 畫布引擎未載入');if(document.fonts?.ready)await document.fonts.ready;const c=await cloneA4();const host=document.createElement('div');host.style.cssText=`position:fixed;left:-12000px;top:0;width:${A4W}px;height:${A4H}px;overflow:hidden;background:#fff;z-index:-99999;pointer-events:none`;host.appendChild(c);document.body.appendChild(host);try{const logo=c.querySelector('img.ub-v21-logo');await new Promise((res,rej)=>{if(logo?.complete&&logo.naturalWidth)return res();if(!logo)return rej(new Error('PDF Logo 不存在'));logo.onload=res;logo.onerror=()=>rej(new Error('PDF Logo 載入失敗'))});await new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r)));const rect=c.getBoundingClientRect();if(Math.abs(rect.width-A4W)>1||Math.abs(rect.height-A4H)>1)throw new Error(`A4 DOM 尺寸錯誤 ${Math.round(rect.width)}×${Math.round(rect.height)}`);const canvas=await window.html2canvas(c,{backgroundColor:'#fff',scale:2,useCORS:false,allowTaint:true,logging:false,width:A4W,height:A4H,windowWidth:A4W,windowHeight:A4H,scrollX:0,scrollY:0});if(canvas.width!==1588||canvas.height!==2246)throw new Error(`A4 畫布尺寸錯誤 ${canvas.width}×${canvas.height}`);return canvas}finally{host.remove()}}
function fileName(){const p=getPaper(),txt=p?.innerText||'';const type=/RECEIPT|收據/i.test(txt)?'Receipt':/INVOICE|付款通知單/i.test(txt)?'Invoice':'Quotation';const no=(txt.match(/(?:QO|TQ|INV|RCP|RC)[A-Z0-9\/-]*/i)||[])[0]||new Date().toISOString().slice(0,10);return `UNIBRIGHT_${type}_${String(no).replace(/[\\/:*?"<>|]+/g,'-')}.pdf`}
async function makePdfBlob(){if(!(window.jspdf&&window.jspdf.jsPDF))throw new Error('PDF 引擎未載入');const canvas=await renderA4Canvas();const {jsPDF}=window.jspdf;const pdf=new jsPDF({orientation:'portrait',unit:'mm',format:'a4',compress:true});pdf.addImage(canvas.toDataURL('image/jpeg',0.99),'JPEG',0,0,210,297,undefined,'FAST');if(pdf.getNumberOfPages()!==1)throw new Error('PDF 唔係單頁 A4');const blob=pdf.output('blob');if(!blob||blob.size<5000)throw new Error('PDF 檔案建立失敗');return blob}
let busy=false;
async function exportPdf(name){if(busy)return false;busy=true;const mobile=/iPhone|iPad|iPod|Android/i.test(navigator.userAgent);let popup=null;try{if(mobile){popup=window.open('about:blank','_blank');if(popup)popup.document.write('<meta name="viewport" content="width=device-width"><p style="font:16px sans-serif;padding:24px">正在建立 A4 PDF…</p>')}const blob=await makePdfBlob();const fn=name||fileName();const url=URL.createObjectURL(blob);if(mobile){if(popup)popup.location.replace(url);else window.location.href=url}else{const a=document.createElement('a');a.href=url;a.download=fn;document.body.appendChild(a);a.click();a.remove()}setTimeout(()=>URL.revokeObjectURL(url),300000);return true}catch(e){try{popup?.close()}catch(_){}console.error('V21 PDF',e);alert('PDF 下載失敗：'+String(e?.message||e));return false}finally{busy=false}}
async function printA4(){const src=getPaper();if(!src){alert('畫面上搵唔到正式 A4 文件');return false}const w=window.open('about:blank','_blank');if(!w){alert('瀏覽器阻止咗列印視窗');return false}try{const c=await cloneA4();w.document.open();w.document.write(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/zoechow412-ui/m@f5f55fb1b62550121a2053b213d4248ed31a028f/unibright-ops/v15/a4-approved.css"><style>html,body{margin:0!important;padding:0!important;width:210mm!important;height:297mm!important;overflow:hidden!important;background:#fff!important}.a4-sheet{width:210mm!important;height:297mm!important;min-height:297mm!important;max-height:297mm!important;margin:0!important;transform:none!important;box-shadow:none!important;overflow:hidden!important;box-sizing:border-box!important}@page{size:A4 portrait;margin:0}</style></head><body>${c.outerHTML}<script>window.onload=()=>setTimeout(()=>{window.focus();window.print()},500)<\/script></body></html>`);w.document.close();return true}catch(e){w.close();alert('列印失敗：'+String(e?.message||e));return false}}
window.exportCurrentPDF=window.downloadCurrentPDF=exportPdf;window.printCurrentA4=window.printA4=printA4;
window.addEventListener('click',e=>{const b=e.target.closest?.('button');if(!b)return;const t=(b.textContent||'').replace(/\s+/g,' ').trim();const oc=b.getAttribute('onclick')||'';if(t==='下載 PDF'||t==='下載／儲存 PDF'||t==='下載 / 儲存 PDF'||/exportCurrentPDF\(/.test(oc)||/printA4\(/.test(oc)&&/下載|PDF/.test(t)){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();exportPdf();return}if(t==='列印'){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();printA4();return}},true);
const mo=new MutationObserver(()=>requestAnimationFrame(()=>patchAll()));mo.observe(document.getElementById('app')||document.body,{subtree:true,childList:true});window.addEventListener('load',()=>patchAll(),{once:true});setTimeout(patchAll,50);setTimeout(patchAll,500);setTimeout(patchAll,1500);
window.UNIBRIGHT_V21=()=>{const p=getPaper(),r=p?.getBoundingClientRect(),logo=p?.querySelector('img.ub-v21-logo');return{build:window.UNIBRIGHT_BUILD,paper:!!p,displayWidth:Math.round(r?.width||0),logo:!!logo,logoLoaded:!!logo?.naturalWidth,pdf:typeof window.exportCurrentPDF==='function',print:typeof window.printCurrentA4==='function'}};
})();